#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BalanceExporter;

namespace BalanceExporter	
{
	public partial class DatabaseModel : OpenAccessContext, IDatabaseModelUnitOfWork
	{
		private static string connectionStringName = @"ASFuelControlDBConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("DatabaseModel.rlinq");
		
		public DatabaseModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public DatabaseModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public DatabaseModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public DatabaseModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public DatabaseModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Balance> Balances 
		{
			get
			{
				return this.GetAll<Balance>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of DatabaseModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of DatabaseModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IDatabaseModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Balance> Balances
		{
			get;
		}
	}
}
namespace BalanceExporter	
{
	public partial class Balance
	{
		private Guid _balanceId;
		public virtual Guid BalanceId
		{
			get
			{
				return this._balanceId;
			}
			set
			{
				this._balanceId = value;
			}
		}
		
		private DateTime _startDate;
		public virtual DateTime StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime _endDate;
		public virtual DateTime EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private Guid? _lastSale;
		public virtual Guid? LastSale
		{
			get
			{
				return this._lastSale;
			}
			set
			{
				this._lastSale = value;
			}
		}
		
		private Guid? _lastFilling;
		public virtual Guid? LastFilling
		{
			get
			{
				return this._lastFilling;
			}
			set
			{
				this._lastFilling = value;
			}
		}
		
		private string _balanceText;
		public virtual string BalanceText
		{
			get
			{
				return this._balanceText;
			}
			set
			{
				this._balanceText = value;
			}
		}
		
		private Guid _applicationUserId;
		public virtual Guid ApplicationUserId
		{
			get
			{
				return this._applicationUserId;
			}
			set
			{
				this._applicationUserId = value;
			}
		}
		
		private DateTime? _sentDateTime;
		public virtual DateTime? SentDateTime
		{
			get
			{
				return this._sentDateTime;
			}
			set
			{
				this._sentDateTime = value;
			}
		}
		
		private string _responseCode;
		public virtual string ResponseCode
		{
			get
			{
				return this._responseCode;
			}
			set
			{
				this._responseCode = value;
			}
		}
		
		private DateTime? _printDate;
		public virtual DateTime? PrintDate
		{
			get
			{
				return this._printDate;
			}
			set
			{
				this._printDate = value;
			}
		}
		
		private string _documentSign;
		public virtual string DocumentSign
		{
			get
			{
				return this._documentSign;
			}
			set
			{
				this._documentSign = value;
			}
		}
		
	}
}
#pragma warning restore 1591
