namespace ASFuelControl.Windows.UI.SelectionForms
{
    partial class SelectFuelTypeForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn9 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn10 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            this.radButton2 = new Telerik.WinControls.UI.RadButton();
            this.radButton1 = new Telerik.WinControls.UI.RadButton();
            this.fuelTypeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.fuelTypeRadGridView = new Telerik.WinControls.UI.RadGridView();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // radButton2
            // 
            this.radButton2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.radButton2.Location = new System.Drawing.Point(226, 236);
            this.radButton2.Name = "radButton2";
            this.radButton2.Size = new System.Drawing.Size(110, 24);
            this.radButton2.TabIndex = 5;
            this.radButton2.Text = "Άκυρο";
            this.radButton2.Click += new System.EventHandler(this.radButton2_Click);
            // 
            // radButton1
            // 
            this.radButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.radButton1.Location = new System.Drawing.Point(12, 236);
            this.radButton1.Name = "radButton1";
            this.radButton1.Size = new System.Drawing.Size(110, 24);
            this.radButton1.TabIndex = 4;
            this.radButton1.Text = "Επιλογή";
            this.radButton1.Click += new System.EventHandler(this.radButton1_Click);
            // 
            // fuelTypeBindingSource
            // 
            this.fuelTypeBindingSource.DataSource = typeof(ASFuelControl.Data.FuelType);
            // 
            // fuelTypeRadGridView
            // 
            this.fuelTypeRadGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.fuelTypeRadGridView.Location = new System.Drawing.Point(12, 12);
            // 
            // fuelTypeRadGridView
            // 
            this.fuelTypeRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.fuelTypeRadGridView.MasterTemplate.AllowDeleteRow = false;
            this.fuelTypeRadGridView.MasterTemplate.AllowEditRow = false;
            this.fuelTypeRadGridView.MasterTemplate.AutoGenerateColumns = false;
            gridViewTextBoxColumn9.FieldName = "Name";
            gridViewTextBoxColumn9.HeaderText = "Ονομασία";
            gridViewTextBoxColumn9.IsAutoGenerated = true;
            gridViewTextBoxColumn9.Name = "Name";
            gridViewTextBoxColumn9.Width = 200;
            gridViewTextBoxColumn10.FieldName = "Code";
            gridViewTextBoxColumn10.HeaderText = "Κωδικός";
            gridViewTextBoxColumn10.IsAutoGenerated = true;
            gridViewTextBoxColumn10.Name = "Code";
            gridViewTextBoxColumn10.Width = 80;
            this.fuelTypeRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn9,
            gridViewTextBoxColumn10});
            this.fuelTypeRadGridView.MasterTemplate.DataSource = this.fuelTypeBindingSource;
            this.fuelTypeRadGridView.Name = "fuelTypeRadGridView";
            this.fuelTypeRadGridView.ShowGroupPanel = false;
            this.fuelTypeRadGridView.Size = new System.Drawing.Size(324, 218);
            this.fuelTypeRadGridView.TabIndex = 6;
            this.fuelTypeRadGridView.Text = "radGridView1";
            // 
            // SelectFuelTypeForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(348, 272);
            this.ControlBox = false;
            this.Controls.Add(this.fuelTypeRadGridView);
            this.Controls.Add(this.radButton2);
            this.Controls.Add(this.radButton1);
            this.Name = "SelectFuelTypeForm";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.Text = "Επιλογή Καυσίμου";
            this.Load += new System.EventHandler(this.SelectFuelTypeForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.fuelTypeRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadButton radButton2;
        private Telerik.WinControls.UI.RadButton radButton1;
        private System.Windows.Forms.BindingSource fuelTypeBindingSource;
        private Telerik.WinControls.UI.RadGridView fuelTypeRadGridView;
    }
}