namespace ASFuelControl.Windows.UI.SelectionForms
{
    partial class SelectInvoiceControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewCommandColumn gridViewCommandColumn1 = new Telerik.WinControls.UI.GridViewCommandColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCommandColumn gridViewCommandColumn2 = new Telerik.WinControls.UI.GridViewCommandColumn();
            this.invoiceLineRadGridView = new Telerik.WinControls.UI.RadGridView();
            this.invoiceLineBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // invoiceLineRadGridView
            // 
            this.invoiceLineRadGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.invoiceLineRadGridView.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.invoiceLineRadGridView.Location = new System.Drawing.Point(0, 0);
            // 
            // invoiceLineRadGridView
            // 
            this.invoiceLineRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.invoiceLineRadGridView.MasterTemplate.AllowDeleteRow = false;
            this.invoiceLineRadGridView.MasterTemplate.AutoGenerateColumns = false;
            gridViewCommandColumn1.HeaderText = "";
            gridViewCommandColumn1.Image = global::ASFuelControl.Windows.Properties.Resources.Search_small;
            gridViewCommandColumn1.Name = "openInvoice";
            gridViewCommandColumn1.Width = 30;
            gridViewTextBoxColumn1.DataType = typeof(System.Guid);
            gridViewTextBoxColumn1.FieldName = "InvoiceId";
            gridViewTextBoxColumn1.HeaderText = " Παραστατικό";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "InvoiceId";
            gridViewTextBoxColumn1.Width = 200;
            gridViewTextBoxColumn2.DataType = typeof(System.Guid);
            gridViewTextBoxColumn2.FieldName = "FuelTypeId";
            gridViewTextBoxColumn2.HeaderText = "Καύσιμο";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "FuelTypeId";
            gridViewTextBoxColumn2.Width = 180;
            gridViewDecimalColumn1.FieldName = "Volume";
            gridViewDecimalColumn1.HeaderText = "Όγκος";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "Volume";
            gridViewDecimalColumn1.Width = 90;
            gridViewDecimalColumn2.FieldName = "VolumeNormalized";
            gridViewDecimalColumn2.HeaderText = "Ογκος 15οC";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "VolumeNormalized";
            gridViewDecimalColumn2.Width = 90;
            gridViewDecimalColumn3.DecimalPlaces = 5;
            gridViewDecimalColumn3.FieldName = "UnitPrice";
            gridViewDecimalColumn3.FormatString = "{0:N5}";
            gridViewDecimalColumn3.HeaderText = "Τιμή Λίτρου";
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "UnitPrice";
            gridViewDecimalColumn3.Width = 90;
            gridViewTextBoxColumn3.FieldName = "Tank.Description";
            gridViewTextBoxColumn3.HeaderText = "Δεξαμενή";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "TankId";
            gridViewTextBoxColumn3.Width = 120;
            gridViewCommandColumn2.DefaultText = "Επιλογή";
            gridViewCommandColumn2.HeaderText = "";
            gridViewCommandColumn2.Name = "column1";
            gridViewCommandColumn2.UseDefaultText = true;
            gridViewCommandColumn2.Width = 80;
            this.invoiceLineRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewCommandColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewDecimalColumn1,
            gridViewDecimalColumn2,
            gridViewDecimalColumn3,
            gridViewTextBoxColumn3,
            gridViewCommandColumn2});
            this.invoiceLineRadGridView.MasterTemplate.DataSource = this.invoiceLineBindingSource;
            this.invoiceLineRadGridView.Name = "invoiceLineRadGridView";
            this.invoiceLineRadGridView.ReadOnly = true;
            this.invoiceLineRadGridView.ShowGroupPanel = false;
            this.invoiceLineRadGridView.Size = new System.Drawing.Size(914, 375);
            this.invoiceLineRadGridView.TabIndex = 1;
            this.invoiceLineRadGridView.Text = "radGridView1";
            this.invoiceLineRadGridView.CommandCellClick += new Telerik.WinControls.UI.CommandCellClickEventHandler(this.invoiceLineRadGridView_CommandCellClick);
            // 
            // invoiceLineBindingSource
            // 
            this.invoiceLineBindingSource.DataSource = typeof(ASFuelControl.Data.InvoiceLine);
            // 
            // SelectInvoiceControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.invoiceLineRadGridView);
            this.Name = "SelectInvoiceControl";
            this.Size = new System.Drawing.Size(914, 375);
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceLineBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView invoiceLineRadGridView;
        private System.Windows.Forms.BindingSource invoiceLineBindingSource;
    }
}
