delete tanksale
delete InvoiceLine
delete salestransaction
delete invoice
delete tankfilling
delete nozzleflow
delete nozzle
delete invoiceprint
delete Dispenser
delete tankprice
delete usageperiod
delete TitrimetryLevel
delete Titrimetry
delete SystemEventData
delete SystemEvent
delete Tank
delete vehicle
delete trader
delete PendingSend
delete FuelTypePrice
delete balance