delete [dbo].[Option]
delete [dbo].[ApplicationUser]
delete [dbo].[AtgProbeType]
delete [dbo].[AtgProbeProtocol]
delete [dbo].[ChangeLog]
delete [dbo].[Country]
delete [dbo].[DispenserType]
delete [dbo].[DispenserProtocol]
delete [dbo].[FuelType]
delete [dbo].[InvoiceTypeTransform]
delete [dbo].[InvoiceType]
delete [dbo].[OilCompany]

insert [dbo].[Option] select * from ASFuelControlDB_Old.[dbo].[Option]
insert [dbo].[ApplicationUser] select * from ASFuelControlDB_Old.[dbo].[ApplicationUser]
insert [dbo].[AtgProbeProtocol] select * from ASFuelControlDB_Old.[dbo].[AtgProbeProtocol]
insert [dbo].[AtgProbeType] select * from ASFuelControlDB_Old.[dbo].[AtgProbeType]
insert [dbo].[Country] select * from ASFuelControlDB_Old.[dbo].[Country]
insert [dbo].[DispenserProtocol] select * from ASFuelControlDB_Old.[dbo].[DispenserProtocol]
insert [dbo].[DispenserType] select * from ASFuelControlDB_Old.[dbo].[DispenserType]
insert [dbo].[CommunicationController] select * from ASFuelControlDB_Old.[dbo].[CommunicationController]
insert [dbo].[Dispenser] select * from ASFuelControlDB_Old.[dbo].[Dispenser]
insert [dbo].[FuelType] select * from ASFuelControlDB_Old.[dbo].[FuelType]
insert [dbo].[InvoiceType] select * from ASFuelControlDB_Old.[dbo].[InvoiceType]
insert [dbo].[InvoicePrint] select * from ASFuelControlDB_Old.[dbo].[InvoicePrint]
insert [dbo].[InvoiceTypeTransform] select * from ASFuelControlDB_Old.[dbo].[InvoiceTypeTransform]
insert [dbo].[OilCompany] select * from ASFuelControlDB_Old.[dbo].[OilCompany]
insert [dbo].[Tank] select * from ASFuelControlDB_Old.[dbo].[Tank]
insert [dbo].[TankSetting] select * from ASFuelControlDB_Old.[dbo].[TankSetting]
insert [dbo].[Titrimetry] select * from ASFuelControlDB_Old.[dbo].[Titrimetry]
insert [dbo].[TitrimetryLevel] select * from ASFuelControlDB_Old.[dbo].[TitrimetryLevel]
insert [dbo].[Nozzle] select * from ASFuelControlDB_Old.[dbo].[Nozzle]
insert [dbo].[NozzleFlow] select * from ASFuelControlDB_Old.[dbo].[NozzleFlow]
insert [dbo].[DeviceSetting] select * from ASFuelControlDB_Old.[dbo].[DeviceSetting]
insert [dbo].[Trader] select * from ASFuelControlDB_Old.[dbo].[Trader]
insert [dbo].[Vehicle] select * from ASFuelControlDB_Old.[dbo].[Vehicle]
