//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Controller {
    
    private ControllerWorkFlowStep[] workFlowField;
    
    private ControllerStatus[] statusesField;
    
    private string typeField;
    
    private ushort baudRateField;
    
    private string parityField;
    
    private string stopBitsField;
    
    private byte dataBitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkFlowStep", IsNullable=false)]
    public ControllerWorkFlowStep[] WorkFlow {
        get {
            return this.workFlowField;
        }
        set {
            this.workFlowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
    public ControllerStatus[] Statuses {
        get {
            return this.statusesField;
        }
        set {
            this.statusesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort BaudRate {
        get {
            return this.baudRateField;
        }
        set {
            this.baudRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Parity {
        get {
            return this.parityField;
        }
        set {
            this.parityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StopBits {
        get {
            return this.stopBitsField;
        }
        set {
            this.stopBitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte DataBits {
        get {
            return this.dataBitsField;
        }
        set {
            this.dataBitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStep {
    
    private ControllerWorkFlowStepMethod[] methodField;
    
    private string conditionField;
    
    private string breakLoopField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Method")]
    public ControllerWorkFlowStepMethod[] Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BreakLoop {
        get {
            return this.breakLoopField;
        }
        set {
            this.breakLoopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethod {
    
    private ControllerWorkFlowStepMethodWrite[] writeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Write")]
    public ControllerWorkFlowStepMethodWrite[] Write {
        get {
            return this.writeField;
        }
        set {
            this.writeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWrite {
    
    private ControllerWorkFlowStepMethodWriteGetMethods getMethodsField;
    
    private ControllerWorkFlowStepMethodWriteEvaluation[] evaluationField;
    
    private string dataField;
    
    /// <remarks/>
    public ControllerWorkFlowStepMethodWriteGetMethods GetMethods {
        get {
            return this.getMethodsField;
        }
        set {
            this.getMethodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Evaluation")]
    public ControllerWorkFlowStepMethodWriteEvaluation[] Evaluation {
        get {
            return this.evaluationField;
        }
        set {
            this.evaluationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteGetMethods {
    
    private ControllerWorkFlowStepMethodWriteGetMethodsGetAddress[] getAddressField;
    
    private ControllerWorkFlowStepMethodWriteGetMethodsGetPriceBuffer[] getPriceBufferField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetAddress")]
    public ControllerWorkFlowStepMethodWriteGetMethodsGetAddress[] GetAddress {
        get {
            return this.getAddressField;
        }
        set {
            this.getAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetPriceBuffer")]
    public ControllerWorkFlowStepMethodWriteGetMethodsGetPriceBuffer[] GetPriceBuffer {
        get {
            return this.getPriceBufferField;
        }
        set {
            this.getPriceBufferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteGetMethodsGetAddress {
    
    private byte param1Field;
    
    private byte param2Field;
    
    private byte returnIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Param1 {
        get {
            return this.param1Field;
        }
        set {
            this.param1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Param2 {
        get {
            return this.param2Field;
        }
        set {
            this.param2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ReturnIndex {
        get {
            return this.returnIndexField;
        }
        set {
            this.returnIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteGetMethodsGetPriceBuffer {
    
    private byte returnIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ReturnIndex {
        get {
            return this.returnIndexField;
        }
        set {
            this.returnIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteEvaluation {
    
    private ControllerWorkFlowStepMethodWriteEvaluationGetMethods getMethodsField;
    
    private string responseField;
    
    private byte skipField;
    
    private byte takeField;
    
    private string methodField;
    
    /// <remarks/>
    public ControllerWorkFlowStepMethodWriteEvaluationGetMethods GetMethods {
        get {
            return this.getMethodsField;
        }
        set {
            this.getMethodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Skip {
        get {
            return this.skipField;
        }
        set {
            this.skipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Take {
        get {
            return this.takeField;
        }
        set {
            this.takeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteEvaluationGetMethods {
    
    private ControllerWorkFlowStepMethodWriteEvaluationGetMethodsGetAddress getAddressField;
    
    /// <remarks/>
    public ControllerWorkFlowStepMethodWriteEvaluationGetMethodsGetAddress GetAddress {
        get {
            return this.getAddressField;
        }
        set {
            this.getAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerWorkFlowStepMethodWriteEvaluationGetMethodsGetAddress {
    
    private byte param1Field;
    
    private byte param2Field;
    
    private byte returnIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Param1 {
        get {
            return this.param1Field;
        }
        set {
            this.param1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Param2 {
        get {
            return this.param2Field;
        }
        set {
            this.param2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ReturnIndex {
        get {
            return this.returnIndexField;
        }
        set {
            this.returnIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerStatus {
    
    private string dataField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
