//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.VirtualDevices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.VirtualDevices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Καυσίμου.
        /// </summary>
        internal static string AlertData_CurrentFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θερμοκρασία Δεξαμενής.
        /// </summary>
        internal static string AlertData_CurrentTemperature {
            get {
                return ResourceManager.GetString("AlertData_CurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρέχων Όγκος Δεξαμενής.
        /// </summary>
        internal static string AlertData_CurrentVolume {
            get {
                return ResourceManager.GetString("AlertData_CurrentVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Νερού.
        /// </summary>
        internal static string AlertData_CurrentWaterLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελευταία στάθμη καυσίμου.
        /// </summary>
        internal static string AlertData_LastFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_LastFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενη Θερμοκρασία Δεξαμενής.
        /// </summary>
        internal static string AlertData_LastTemperature {
            get {
                return ResourceManager.GetString("AlertData_LastTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενος Όγκος Δεξαμενής.
        /// </summary>
        internal static string AlertData_LastVolume {
            get {
                return ResourceManager.GetString("AlertData_LastVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελευταίος συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_LastVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_LastVolumeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MaxHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστη επιτρεπόμενη στάθμη Νερού.
        /// </summary>
        internal static string AlertData_MaxWaterHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxWaterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελάχιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MinHeight {
            get {
                return ResourceManager.GetString("AlertData_MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πυκνότητα Καυσίμου.
        /// </summary>
        internal static string AlertData_TankDensityError {
            get {
                return ResourceManager.GetString("AlertData_TankDensityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_TotalVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_TotalVolumeCounter", resourceCulture);
            }
        }
    }
}
