//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαφορά Ισοζυγίου.
        /// </summary>
        internal static string AlertTypeEnum_BalanceDifference {
            get {
                return ResourceManager.GetString("AlertTypeEnum_BalanceDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Συνδεσης Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_CommunicationLossFuelPoint {
            get {
                return ResourceManager.GetString("AlertTypeEnum_CommunicationLossFuelPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Συνδεσης Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_CommunicationLossTank {
            get {
                return ResourceManager.GetString("AlertTypeEnum_CommunicationLossTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδικαιολόγητη Απώλεια καυσίμου.
        /// </summary>
        internal static string AlertTypeEnum_FuelLoss {
            get {
                return ResourceManager.GetString("AlertTypeEnum_FuelLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_FuelPointError {
            get {
                return ResourceManager.GetString("AlertTypeEnum_FuelPointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διακοπή λειτουργίας προγράμματος.
        /// </summary>
        internal static string AlertTypeEnum_ProgramTermination {
            get {
                return ResourceManager.GetString("AlertTypeEnum_ProgramTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_TankAlert {
            get {
                return ResourceManager.GetString("AlertTypeEnum_TankAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Ογκομετρικού Πίνακα.
        /// </summary>
        internal static string AlertTypeEnum_TitrimetryDataChange {
            get {
                return ResourceManager.GetString("AlertTypeEnum_TitrimetryDataChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεδομένων Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_WrongDataFuelPoint {
            get {
                return ResourceManager.GetString("AlertTypeEnum_WrongDataFuelPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεδομένων Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_WrongDataTank {
            get {
                return ResourceManager.GetString("AlertTypeEnum_WrongDataTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γενικός Διαχειρηστής.
        /// </summary>
        internal static string ApplicationUserLevelEnum_Administrator {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συσκευή.
        /// </summary>
        internal static string ApplicationUserLevelEnum_Device {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαχειρηστής.
        /// </summary>
        internal static string ApplicationUserLevelEnum_SuperUser {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_SuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρήστης.
        /// </summary>
        internal static string ApplicationUserLevelEnum_User {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentLoop.
        /// </summary>
        internal static string CommunicationTypeEnum_CurrentLoop {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_CurrentLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS232.
        /// </summary>
        internal static string CommunicationTypeEnum_RS232 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS422.
        /// </summary>
        internal static string CommunicationTypeEnum_RS422 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485.
        /// </summary>
        internal static string CommunicationTypeEnum_RS485 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS485", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Στόμιο στο κανάλι {0} με διεύθυνση {1} έχει {2} λίτρα διαφορά..
        /// </summary>
        internal static string EventType_NozzleTotalDifference {
            get {
                return ResourceManager.GetString("EventType_NozzleTotalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Δεξαμενή στο κανάλι {0} με διεύθυνση {1} έχει {2} λίτρα διαφορά..
        /// </summary>
        internal static string EventType_TankTotalDifference {
            get {
                return ResourceManager.GetString("EventType_TankTotalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλειστή Παροχή.
        /// </summary>
        internal static string FlowStateEnum_ValveClosed {
            get {
                return ResourceManager.GetString("FlowStateEnum_ValveClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανοιχτή Παροχή.
        /// </summary>
        internal static string FlowStateEnum_ValveOpen {
            get {
                return ResourceManager.GetString("FlowStateEnum_ValveOpen", resourceCulture);
            }
        }
    }
}
