namespace ASFuelControl.Windows.UI.SelectionForms
{
    partial class SelectInvoiceTypeForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn2 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SelectInvoiceTypeForm));
            this.invoiceTypeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.invoiceTypeRadGridView = new Telerik.WinControls.UI.RadGridView();
            this.radButton1 = new Telerik.WinControls.UI.RadButton();
            this.radButton2 = new Telerik.WinControls.UI.RadButton();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // invoiceTypeBindingSource
            // 
            this.invoiceTypeBindingSource.DataSource = typeof(ASFuelControl.Data.InvoiceType);
            // 
            // invoiceTypeRadGridView
            // 
            this.invoiceTypeRadGridView.Location = new System.Drawing.Point(12, 12);
            // 
            // invoiceTypeRadGridView
            // 
            this.invoiceTypeRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.invoiceTypeRadGridView.MasterTemplate.AllowDeleteRow = false;
            this.invoiceTypeRadGridView.MasterTemplate.AutoGenerateColumns = false;
            gridViewTextBoxColumn3.FieldName = "Description";
            gridViewTextBoxColumn3.HeaderText = "Περιγραφή";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "Description";
            gridViewTextBoxColumn3.Width = 200;
            gridViewTextBoxColumn4.FieldName = "Abbreviation";
            gridViewTextBoxColumn4.HeaderText = "Συντόμευση";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "Abbreviation";
            gridViewTextBoxColumn4.Width = 90;
            gridViewDecimalColumn2.DataType = typeof(int);
            gridViewDecimalColumn2.FieldName = "LastNumber";
            gridViewDecimalColumn2.HeaderText = "Α/Α";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "LastNumber";
            gridViewCheckBoxColumn2.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn2.FieldName = "IsInternal";
            gridViewCheckBoxColumn2.HeaderText = "Εσωτερικό";
            gridViewCheckBoxColumn2.IsAutoGenerated = true;
            gridViewCheckBoxColumn2.Name = "IsInternal";
            gridViewCheckBoxColumn2.Width = 90;
            this.invoiceTypeRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewDecimalColumn2,
            gridViewCheckBoxColumn2});
            this.invoiceTypeRadGridView.MasterTemplate.DataSource = this.invoiceTypeBindingSource;
            this.invoiceTypeRadGridView.Name = "invoiceTypeRadGridView";
            this.invoiceTypeRadGridView.ReadOnly = true;
            this.invoiceTypeRadGridView.ShowGroupPanel = false;
            this.invoiceTypeRadGridView.Size = new System.Drawing.Size(467, 223);
            this.invoiceTypeRadGridView.TabIndex = 1;
            this.invoiceTypeRadGridView.Text = "radGridView1";
            // 
            // radButton1
            // 
            this.radButton1.Location = new System.Drawing.Point(12, 241);
            this.radButton1.Name = "radButton1";
            this.radButton1.Size = new System.Drawing.Size(110, 24);
            this.radButton1.TabIndex = 2;
            this.radButton1.Text = "Επιλογή";
            this.radButton1.Click += new System.EventHandler(this.radButton1_Click);
            // 
            // radButton2
            // 
            this.radButton2.Location = new System.Drawing.Point(369, 241);
            this.radButton2.Name = "radButton2";
            this.radButton2.Size = new System.Drawing.Size(110, 24);
            this.radButton2.TabIndex = 3;
            this.radButton2.Text = "Άκυρο";
            this.radButton2.Click += new System.EventHandler(this.radButton2_Click);
            // 
            // SelectInvoiceTypeForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(491, 273);
            this.ControlBox = false;
            this.Controls.Add(this.radButton2);
            this.Controls.Add(this.radButton1);
            this.Controls.Add(this.invoiceTypeRadGridView);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "SelectInvoiceTypeForm";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Επιλογή Τύπου Παραστατικού";
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.invoiceTypeRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource invoiceTypeBindingSource;
        private Telerik.WinControls.UI.RadGridView invoiceTypeRadGridView;
        private Telerik.WinControls.UI.RadButton radButton1;
        private Telerik.WinControls.UI.RadButton radButton2;
    }
}