namespace ASFuelControl.Windows.UI.SettingForms
{
    partial class SerialNumbersForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            this.deviceSettingBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.deviceSettingRadGridView = new Telerik.WinControls.UI.RadGridView();
            this.radButton1 = new Telerik.WinControls.UI.RadButton();
            this.radButton2 = new Telerik.WinControls.UI.RadButton();
            this.radButton3 = new Telerik.WinControls.UI.RadButton();
            this.radButton4 = new Telerik.WinControls.UI.RadButton();
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // deviceSettingBindingSource
            // 
            this.deviceSettingBindingSource.DataSource = typeof(ASFuelControl.Data.DeviceSetting);
            // 
            // deviceSettingRadGridView
            // 
            this.deviceSettingRadGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.deviceSettingRadGridView.Location = new System.Drawing.Point(12, 56);
            // 
            // deviceSettingRadGridView
            // 
            this.deviceSettingRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.deviceSettingRadGridView.MasterTemplate.AllowDeleteRow = false;
            this.deviceSettingRadGridView.MasterTemplate.AutoGenerateColumns = false;
            gridViewTextBoxColumn1.FieldName = "Description";
            gridViewTextBoxColumn1.HeaderText = "Περιγρφή";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Description";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 250;
            gridViewTextBoxColumn2.FieldName = "DeviceTypeDescription";
            gridViewTextBoxColumn2.HeaderText = "Είδος Συσκευής";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "DeviceType";
            gridViewTextBoxColumn2.ReadOnly = true;
            gridViewTextBoxColumn2.Width = 150;
            gridViewTextBoxColumn3.FieldName = "SettingValue";
            gridViewTextBoxColumn3.HeaderText = "Τιμή";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "SettingValue";
            gridViewTextBoxColumn3.Width = 250;
            this.deviceSettingRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3});
            this.deviceSettingRadGridView.MasterTemplate.DataSource = this.deviceSettingBindingSource;
            this.deviceSettingRadGridView.Name = "deviceSettingRadGridView";
            this.deviceSettingRadGridView.Size = new System.Drawing.Size(688, 411);
            this.deviceSettingRadGridView.TabIndex = 1;
            this.deviceSettingRadGridView.Text = "radGridView1";
            // 
            // radButton1
            // 
            this.radButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.radButton1.Location = new System.Drawing.Point(590, 473);
            this.radButton1.Name = "radButton1";
            this.radButton1.Size = new System.Drawing.Size(110, 24);
            this.radButton1.TabIndex = 2;
            this.radButton1.Text = "Κλείσιμο";
            this.radButton1.Click += new System.EventHandler(this.radButton1_Click);
            // 
            // radButton2
            // 
            this.radButton2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.radButton2.Location = new System.Drawing.Point(12, 473);
            this.radButton2.Name = "radButton2";
            this.radButton2.Size = new System.Drawing.Size(110, 24);
            this.radButton2.TabIndex = 3;
            this.radButton2.Text = "Εκτύπωση";
            this.radButton2.Click += new System.EventHandler(this.radButton2_Click);
            // 
            // radButton3
            // 
            this.radButton3.Image = global::ASFuelControl.Windows.Properties.Resources.Add;
            this.radButton3.Location = new System.Drawing.Point(12, 12);
            this.radButton3.Name = "radButton3";
            this.radButton3.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.radButton3.Size = new System.Drawing.Size(110, 38);
            this.radButton3.TabIndex = 4;
            this.radButton3.Text = "Προσθήκη";
            this.radButton3.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.radButton3.Click += new System.EventHandler(this.radButton3_Click);
            // 
            // radButton4
            // 
            this.radButton4.Image = global::ASFuelControl.Windows.Properties.Resources.Delete;
            this.radButton4.Location = new System.Drawing.Point(128, 12);
            this.radButton4.Name = "radButton4";
            this.radButton4.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.radButton4.Size = new System.Drawing.Size(110, 38);
            this.radButton4.TabIndex = 5;
            this.radButton4.Text = "Διαγραφή";
            this.radButton4.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.radButton4.Click += new System.EventHandler(this.radButton4_Click);
            // 
            // SerialNumbersForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(712, 509);
            this.Controls.Add(this.radButton4);
            this.Controls.Add(this.radButton3);
            this.Controls.Add(this.radButton2);
            this.Controls.Add(this.radButton1);
            this.Controls.Add(this.deviceSettingRadGridView);
            this.MinimumSize = new System.Drawing.Size(720, 350);
            this.Name = "SerialNumbersForm";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Σειριακοί Αριθμοί";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.SerialNumbersForm_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.deviceSettingRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource deviceSettingBindingSource;
        private Telerik.WinControls.UI.RadGridView deviceSettingRadGridView;
        private Telerik.WinControls.UI.RadButton radButton1;
        private Telerik.WinControls.UI.RadButton radButton2;
        private Telerik.WinControls.UI.RadButton radButton3;
        private Telerik.WinControls.UI.RadButton radButton4;
    }
}