//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Καυσίμου.
        /// </summary>
        internal static string AlertData_CurrentFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Νερού.
        /// </summary>
        internal static string AlertData_CurrentWaterLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελευταία στάθμη καυσίμου.
        /// </summary>
        internal static string AlertData_LastFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_LastFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελευταίος συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_LastVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_LastVolumeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MaxHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστη επιτρεπόμενη στάθμη Νερού.
        /// </summary>
        internal static string AlertData_MaxWaterHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxWaterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελάχιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MinHeight {
            get {
                return ResourceManager.GetString("AlertData_MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_TotalVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_TotalVolumeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Αναγωγή στους 15ο C δεν είναι σωστή. Η ανεγαγμένη ποσότητα στους 15ο C θα έπρεπε να είναι {0:N2}.
        /// </summary>
        internal static string InvoiceLine_RecieveNormalizationError {
            get {
                return ResourceManager.GetString("InvoiceLine_RecieveNormalizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχει τιμή για τον επιλεμένο τύπο καυσίμου ({0})..
        /// </summary>
        internal static string SalesTransactionValidator_FuelTypePriceNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_FuelTypePriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε τιμή για την πώληση που κάνετε..
        /// </summary>
        internal static string SalesTransactionValidator_NozzlePriceNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_NozzlePriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε άνοιγμα περιόδου για το στόμιο {0}..
        /// </summary>
        internal static string SalesTransactionValidator_NozzleUsagePriodNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_NozzleUsagePriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπόρεσε να δημιουργηθεί καταχώρηση τιμής για την δεξαμενή {0}..
        /// </summary>
        internal static string TankFillingValidator_TankPriceCreationFailed {
            get {
                return ResourceManager.GetString("TankFillingValidator_TankPriceCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε άνοιγμα περιόδου για την δεξαμενή {0}..
        /// </summary>
        internal static string TankFillingValidator_TankUsagePriodNotFound {
            get {
                return ResourceManager.GetString("TankFillingValidator_TankUsagePriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε ανοιχτή χρήση για την {0:ddd dd/MM/yyyy}...
        /// </summary>
        internal static string UsagePeriod_PerioNotFound {
            get {
                return ResourceManager.GetString("UsagePeriod_PerioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H περίοδος χρήσης της εγγραφής είναι κλειδωμένη. Δεν έγιναν αλλαγές...
        /// </summary>
        internal static string UsagePeriodLocked {
            get {
                return ResourceManager.GetString("UsagePeriodLocked", resourceCulture);
            }
        }
    }
}
