//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Windows.SmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.SmsStatusReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.SmsBaseStatusReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.BalanceReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.UserReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.PurchaseReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.MainBalanceReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASFuelControl.Windows.SmsService.SmsSendReturn))]
    public partial class ServiceReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASFuelControl.Windows.SmsService.ReturnTypeEnum ReturnTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASFuelControl.Windows.SmsService.ReturnTypeEnum ReturnType {
            get {
                return this.ReturnTypeField;
            }
            set {
                if ((this.ReturnTypeField.Equals(value) != true)) {
                    this.ReturnTypeField = value;
                    this.RaisePropertyChanged("ReturnType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsStatusReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class SmsStatusReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASFuelControl.Windows.SmsService.MessageDeliveryResponse ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASFuelControl.Windows.SmsService.MessageDeliveryResponse Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsBaseStatusReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class SmsBaseStatusReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDeliveredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeDescription {
            get {
                return this.CodeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeDescriptionField, value) != true)) {
                    this.CodeDescriptionField = value;
                    this.RaisePropertyChanged("CodeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDelivered {
            get {
                return this.DateDeliveredField;
            }
            set {
                if ((this.DateDeliveredField.Equals(value) != true)) {
                    this.DateDeliveredField = value;
                    this.RaisePropertyChanged("DateDelivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSent {
            get {
                return this.DateSentField;
            }
            set {
                if ((this.DateSentField.Equals(value) != true)) {
                    this.DateSentField = value;
                    this.RaisePropertyChanged("DateSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class BalanceReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class UserReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASFuelControl.Windows.SmsService.CustomerView[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASFuelControl.Windows.SmsService.CustomerView[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class PurchaseReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASFuelControl.Windows.SmsService.PurchaseView[] PurchasesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASFuelControl.Windows.SmsService.PurchaseView[] Purchases {
            get {
                return this.PurchasesField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchasesField, value) != true)) {
                    this.PurchasesField = value;
                    this.RaisePropertyChanged("Purchases");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainBalanceReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class MainBalanceReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MainBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MainBalance {
            get {
                return this.MainBalanceField;
            }
            set {
                if ((this.MainBalanceField.Equals(value) != true)) {
                    this.MainBalanceField = value;
                    this.RaisePropertyChanged("MainBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SumBalance {
            get {
                return this.SumBalanceField;
            }
            set {
                if ((this.SumBalanceField.Equals(value) != true)) {
                    this.SumBalanceField = value;
                    this.RaisePropertyChanged("SumBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendReturn", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSService")]
    [System.SerializableAttribute()]
    public partial class SmsSendReturn : ASFuelControl.Windows.SmsService.ServiceReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSMessageIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSMessageId {
            get {
                return this.SMSMessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSMessageIdField, value) != true)) {
                    this.SMSMessageIdField = value;
                    this.RaisePropertyChanged("SMSMessageId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSDAL")]
    public enum ReturnTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNameExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordValidation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameValidation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailValidation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerNotFound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerCellPhoneNotFound = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerCellPhoneInvalid = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentMethodNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidatedPhoneNumber = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralError = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNotFound = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignMemberFound = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAlreadyStarted = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellPhoneListNotFound = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongCountryPrefix = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutOfCredits = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutOfCreditsMainApplication = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FilterShort = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAllowed = 21,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDeliveryResponse", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSDAL")]
    [System.SerializableAttribute()]
    public partial class MessageDeliveryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MccMncField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TrackedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] EID {
            get {
                return this.EIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EIDField, value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinal {
            get {
                return this.IsFinalField;
            }
            set {
                if ((this.IsFinalField.Equals(value) != true)) {
                    this.IsFinalField = value;
                    this.RaisePropertyChanged("IsFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MccMnc {
            get {
                return this.MccMncField;
            }
            set {
                if ((object.ReferenceEquals(this.MccMncField, value) != true)) {
                    this.MccMncField = value;
                    this.RaisePropertyChanged("MccMnc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TrackedDate {
            get {
                return this.TrackedDateField;
            }
            set {
                if ((this.TrackedDateField.Equals(value) != true)) {
                    this.TrackedDateField = value;
                    this.RaisePropertyChanged("TrackedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerView", Namespace="http://schemas.datacontract.org/2004/07/CampaignModel")]
    [System.SerializableAttribute()]
    public partial class CustomerView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditsPerEuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PriceListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxRegistrationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreditsBalance {
            get {
                return this.CreditsBalanceField;
            }
            set {
                if ((this.CreditsBalanceField.Equals(value) != true)) {
                    this.CreditsBalanceField = value;
                    this.RaisePropertyChanged("CreditsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreditsPerEuro {
            get {
                return this.CreditsPerEuroField;
            }
            set {
                if ((this.CreditsPerEuroField.Equals(value) != true)) {
                    this.CreditsPerEuroField = value;
                    this.RaisePropertyChanged("CreditsPerEuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PriceListId {
            get {
                return this.PriceListIdField;
            }
            set {
                if ((this.PriceListIdField.Equals(value) != true)) {
                    this.PriceListIdField = value;
                    this.RaisePropertyChanged("PriceListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIdField, value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxOffice {
            get {
                return this.TaxOfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxOfficeField, value) != true)) {
                    this.TaxOfficeField = value;
                    this.RaisePropertyChanged("TaxOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxRegistrationNumber {
            get {
                return this.TaxRegistrationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxRegistrationNumberField, value) != true)) {
                    this.TaxRegistrationNumberField = value;
                    this.RaisePropertyChanged("TaxRegistrationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseView", Namespace="http://schemas.datacontract.org/2004/07/CampaignModel")]
    [System.SerializableAttribute()]
    public partial class PurchaseView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentMethodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProcessingFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PurchasePackageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SMSCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VATField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentMethodId {
            get {
                return this.PaymentMethodIdField;
            }
            set {
                if ((this.PaymentMethodIdField.Equals(value) != true)) {
                    this.PaymentMethodIdField = value;
                    this.RaisePropertyChanged("PaymentMethodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((this.PaymentTypeField.Equals(value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProcessingFee {
            get {
                return this.ProcessingFeeField;
            }
            set {
                if ((this.ProcessingFeeField.Equals(value) != true)) {
                    this.ProcessingFeeField = value;
                    this.RaisePropertyChanged("ProcessingFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseId {
            get {
                return this.PurchaseIdField;
            }
            set {
                if ((this.PurchaseIdField.Equals(value) != true)) {
                    this.PurchaseIdField = value;
                    this.RaisePropertyChanged("PurchaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PurchasePackageId {
            get {
                return this.PurchasePackageIdField;
            }
            set {
                if ((this.PurchasePackageIdField.Equals(value) != true)) {
                    this.PurchasePackageIdField = value;
                    this.RaisePropertyChanged("PurchasePackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SMSCredits {
            get {
                return this.SMSCreditsField;
            }
            set {
                if ((this.SMSCreditsField.Equals(value) != true)) {
                    this.SMSCreditsField = value;
                    this.RaisePropertyChanged("SMSCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VAT {
            get {
                return this.VATField;
            }
            set {
                if ((this.VATField.Equals(value) != true)) {
                    this.VATField = value;
                    this.RaisePropertyChanged("VAT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/ExedronSMSDAL")]
    public enum PaymentTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditCard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Google = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankTransfer = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendSms", ReplyAction="http://tempuri.org/IService1/SendSmsResponse")]
        ASFuelControl.Windows.SmsService.SmsSendReturn SendSms(string username, string password, string message, string reciever);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendBatchSms", ReplyAction="http://tempuri.org/IService1/SendBatchSmsResponse")]
        ASFuelControl.Windows.SmsService.SmsSendReturn[] SendBatchSms(string username, string password, string message, string[] recievers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendBatchSmsDate", ReplyAction="http://tempuri.org/IService1/SendBatchSmsDateResponse")]
        ASFuelControl.Windows.SmsService.SmsSendReturn[] SendBatchSmsDate(string username, string password, string message, string[] recievers, System.DateTime dtSned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSmsStatus", ReplyAction="http://tempuri.org/IService1/GetSmsStatusResponse")]
        ASFuelControl.Windows.SmsService.SmsStatusReturn GetSmsStatus(string username, string password, string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSmsStatusBatch", ReplyAction="http://tempuri.org/IService1/GetSmsStatusBatchResponse")]
        ASFuelControl.Windows.SmsService.SmsStatusReturn[] GetSmsStatusBatch(string username, string password, string[] messageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSmsBaseStatus", ReplyAction="http://tempuri.org/IService1/GetSmsBaseStatusResponse")]
        ASFuelControl.Windows.SmsService.SmsBaseStatusReturn[] GetSmsBaseStatus(string username, string password, string[] messageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        ASFuelControl.Windows.SmsService.BalanceReturn GetBalance(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCustomer", ReplyAction="http://tempuri.org/IService1/CreateCustomerResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn CreateCustomer(string username, string password, [System.ServiceModel.MessageParameterAttribute(Name="userName")] string userName1, [System.ServiceModel.MessageParameterAttribute(Name="passWord")] string passWord1, string email, string phone, string address, string city, string country, string taxNumber, string taxOffice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        ASFuelControl.Windows.SmsService.UserReturn GetUsers(string username, string password, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomerBalance", ReplyAction="http://tempuri.org/IService1/AddCustomerBalanceResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn AddCustomerBalance(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, decimal balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeCustomer", ReplyAction="http://tempuri.org/IService1/ChangeCustomerResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn ChangeCustomer(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPayment", ReplyAction="http://tempuri.org/IService1/AddPaymentResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn AddPayment(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, decimal amount, ASFuelControl.Windows.SmsService.PaymentTypeEnum ptype, decimal fee, decimal vat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCreditsPayment", ReplyAction="http://tempuri.org/IService1/AddCreditsPaymentResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn AddCreditsPayment(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, int credits, ASFuelControl.Windows.SmsService.PaymentTypeEnum ptype, decimal fee, decimal vat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUser", ReplyAction="http://tempuri.org/IService1/CheckUserResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn CheckUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAmountForCredits", ReplyAction="http://tempuri.org/IService1/GetAmountForCreditsResponse")]
        decimal GetAmountForCredits(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCreditsForAmount", ReplyAction="http://tempuri.org/IService1/GetCreditsForAmountResponse")]
        decimal GetCreditsForAmount(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPurchases", ReplyAction="http://tempuri.org/IService1/GetPurchasesResponse")]
        ASFuelControl.Windows.SmsService.PurchaseReturn GetPurchases(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMainBalance", ReplyAction="http://tempuri.org/IService1/GetMainBalanceResponse")]
        ASFuelControl.Windows.SmsService.MainBalanceReturn GetMainBalance(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePurchase", ReplyAction="http://tempuri.org/IService1/DeletePurchaseResponse")]
        ASFuelControl.Windows.SmsService.ServiceReturn DeletePurchase(string username, string password, ASFuelControl.Windows.SmsService.PurchaseView purchase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ASFuelControl.Windows.SmsService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ASFuelControl.Windows.SmsService.IService1>, ASFuelControl.Windows.SmsService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ASFuelControl.Windows.SmsService.SmsSendReturn SendSms(string username, string password, string message, string reciever) {
            return base.Channel.SendSms(username, password, message, reciever);
        }
        
        public ASFuelControl.Windows.SmsService.SmsSendReturn[] SendBatchSms(string username, string password, string message, string[] recievers) {
            return base.Channel.SendBatchSms(username, password, message, recievers);
        }
        
        public ASFuelControl.Windows.SmsService.SmsSendReturn[] SendBatchSmsDate(string username, string password, string message, string[] recievers, System.DateTime dtSned) {
            return base.Channel.SendBatchSmsDate(username, password, message, recievers, dtSned);
        }
        
        public ASFuelControl.Windows.SmsService.SmsStatusReturn GetSmsStatus(string username, string password, string messageId) {
            return base.Channel.GetSmsStatus(username, password, messageId);
        }
        
        public ASFuelControl.Windows.SmsService.SmsStatusReturn[] GetSmsStatusBatch(string username, string password, string[] messageIds) {
            return base.Channel.GetSmsStatusBatch(username, password, messageIds);
        }
        
        public ASFuelControl.Windows.SmsService.SmsBaseStatusReturn[] GetSmsBaseStatus(string username, string password, string[] messageIds) {
            return base.Channel.GetSmsBaseStatus(username, password, messageIds);
        }
        
        public ASFuelControl.Windows.SmsService.BalanceReturn GetBalance(string username, string password) {
            return base.Channel.GetBalance(username, password);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn CreateCustomer(string username, string password, string userName1, string passWord1, string email, string phone, string address, string city, string country, string taxNumber, string taxOffice) {
            return base.Channel.CreateCustomer(username, password, userName1, passWord1, email, phone, address, city, country, taxNumber, taxOffice);
        }
        
        public ASFuelControl.Windows.SmsService.UserReturn GetUsers(string username, string password, string filter) {
            return base.Channel.GetUsers(username, password, filter);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn AddCustomerBalance(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, decimal balance) {
            return base.Channel.AddCustomerBalance(username, password, customer, balance);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn ChangeCustomer(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer) {
            return base.Channel.ChangeCustomer(username, password, customer);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn AddPayment(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, decimal amount, ASFuelControl.Windows.SmsService.PaymentTypeEnum ptype, decimal fee, decimal vat) {
            return base.Channel.AddPayment(username, password, customer, amount, ptype, fee, vat);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn AddCreditsPayment(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer, int credits, ASFuelControl.Windows.SmsService.PaymentTypeEnum ptype, decimal fee, decimal vat) {
            return base.Channel.AddCreditsPayment(username, password, customer, credits, ptype, fee, vat);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn CheckUser(string username, string password) {
            return base.Channel.CheckUser(username, password);
        }
        
        public decimal GetAmountForCredits(decimal amount) {
            return base.Channel.GetAmountForCredits(amount);
        }
        
        public decimal GetCreditsForAmount(decimal amount) {
            return base.Channel.GetCreditsForAmount(amount);
        }
        
        public ASFuelControl.Windows.SmsService.PurchaseReturn GetPurchases(string username, string password, ASFuelControl.Windows.SmsService.CustomerView customer) {
            return base.Channel.GetPurchases(username, password, customer);
        }
        
        public ASFuelControl.Windows.SmsService.MainBalanceReturn GetMainBalance(string username, string password) {
            return base.Channel.GetMainBalance(username, password);
        }
        
        public ASFuelControl.Windows.SmsService.ServiceReturn DeletePurchase(string username, string password, ASFuelControl.Windows.SmsService.PurchaseView purchase) {
            return base.Channel.DeletePurchase(username, password, purchase);
        }
    }
}
