//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alert {
            get {
                object obj = ResourceManager.GetObject("Alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Border {
            get {
                object obj = ResourceManager.GetObject("Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bottle {
            get {
                object obj = ResourceManager.GetObject("Bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Controller {
            get {
                object obj = ResourceManager.GetObject("Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ////****** Object:  Database [DatabaseName]    Script Date: 06/10/2014 00:20:01 ******/
        ///CREATE DATABASE [DatabaseName] ON  PRIMARY 
        ///( NAME = N&apos;[DatabaseName]&apos;, FILENAME = N&apos;[FileName].mdf&apos; , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        /// LOG ON 
        ///( NAME = N&apos;[DatabaseName]_log&apos;, FILENAME = N&apos;[FileName]_log.ldf&apos; , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
        ///GO
        ///ALTER DATABASE [DatabaseName] SET COMPATIBILITY_LEVEL = 100
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullText [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customers {
            get {
                object obj = ResourceManager.GetObject("Customers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CustomerSelect {
            get {
                object obj = ResourceManager.GetObject("CustomerSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Display {
            get {
                object obj = ResourceManager.GetObject("Display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Drain64 {
            get {
                object obj = ResourceManager.GetObject("Drain64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fill64 {
            get {
                object obj = ResourceManager.GetObject("Fill64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillingCancel {
            get {
                object obj = ResourceManager.GetObject("FillingCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillingEnd {
            get {
                object obj = ResourceManager.GetObject("FillingEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillingStart {
            get {
                object obj = ResourceManager.GetObject("FillingStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fuel_Station {
            get {
                object obj = ResourceManager.GetObject("Fuel_Station", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελεγχος Τιμών.
        /// </summary>
        internal static string FuelPointStatusEnum_CheckState {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_CheckState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα.
        /// </summary>
        internal static string FuelPointStatusEnum_Error {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενημέρωση Αθροιστή.
        /// </summary>
        internal static string FuelPointStatusEnum_GetEndTotals {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_GetEndTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Αδράνεια.
        /// </summary>
        internal static string FuelPointStatusEnum_Idle {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εναρξη Πώλησης.
        /// </summary>
        internal static string FuelPointStatusEnum_InitializeSale {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_InitializeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Αναμονή.
        /// </summary>
        internal static string FuelPointStatusEnum_Nozzle {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Nozzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκτος Λειτουργίας.
        /// </summary>
        internal static string FuelPointStatusEnum_Offline {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έτοιμη προς Πώληση.
        /// </summary>
        internal static string FuelPointStatusEnum_Ready {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκλήρωση Πώλησης.
        /// </summary>
        internal static string FuelPointStatusEnum_SalingCompleted {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_SalingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλειδωμένη Δεξαμενή.
        /// </summary>
        internal static string FuelPointStatusEnum_TankLocked {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_TankLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολοκλήρωση Πώλησης.
        /// </summary>
        internal static string FuelPointStatusEnum_TransactionCompleted {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_TransactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παύση Πώληση .
        /// </summary>
        internal static string FuelPointStatusEnum_TransactionStopped {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_TransactionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πώληση.
        /// </summary>
        internal static string FuelPointStatusEnum_Work {
            get {
                return ResourceManager.GetString("FuelPointStatusEnum_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FuelPump {
            get {
                object obj = ResourceManager.GetObject("FuelPump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FuelPump_128 {
            get {
                object obj = ResourceManager.GetObject("FuelPump_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GeneralSettings {
            get {
                object obj = ResourceManager.GetObject("GeneralSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invoice {
            get {
                object obj = ResourceManager.GetObject("Invoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invoice_100 {
            get {
                object obj = ResourceManager.GetObject("Invoice_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invoice_128 {
            get {
                object obj = ResourceManager.GetObject("Invoice_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainLogo {
            get {
                object obj = ResourceManager.GetObject("MainLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Message {
            get {
                object obj = ResourceManager.GetObject("Message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nozzle {
            get {
                object obj = ResourceManager.GetObject("Nozzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pratiriouxos_gr {
            get {
                object obj = ResourceManager.GetObject("Pratiriouxos_gr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Price {
            get {
                object obj = ResourceManager.GetObject("Price", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prices {
            get {
                object obj = ResourceManager.GetObject("Prices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer_small {
            get {
                object obj = ResourceManager.GetObject("Printer_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrinterBig {
            get {
                object obj = ResourceManager.GetObject("PrinterBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset {
            get {
                object obj = ResourceManager.GetObject("Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveBig {
            get {
                object obj = ResourceManager.GetObject("SaveBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_small {
            get {
                object obj = ResourceManager.GetObject("Search_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsTank {
            get {
                object obj = ResourceManager.GetObject("SettingsTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Statistics {
            get {
                object obj = ResourceManager.GetObject("Statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tank {
            get {
                object obj = ResourceManager.GetObject("Tank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tank_128 {
            get {
                object obj = ResourceManager.GetObject("Tank_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TankIcon {
            get {
                object obj = ResourceManager.GetObject("TankIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεξαμενής.
        /// </summary>
        internal static string TankStatusEnum_Error {
            get {
                return ResourceManager.GetString("TankStatusEnum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραλαβή Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_Filling {
            get {
                return ResourceManager.GetString("TankStatusEnum_Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναμονή Παραλαβής.
        /// </summary>
        internal static string TankStatusEnum_FillingInit {
            get {
                return ResourceManager.GetString("TankStatusEnum_FillingInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_FuelExtraction {
            get {
                return ResourceManager.GetString("TankStatusEnum_FuelExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναμονή Εξαγωγής.
        /// </summary>
        internal static string TankStatusEnum_FuelExtractionInit {
            get {
                return ResourceManager.GetString("TankStatusEnum_FuelExtractionInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υψηλή Στάθμη Νερού.
        /// </summary>
        internal static string TankStatusEnum_HighWaterLevel {
            get {
                return ResourceManager.GetString("TankStatusEnum_HighWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Αδράνεια.
        /// </summary>
        internal static string TankStatusEnum_Idle {
            get {
                return ResourceManager.GetString("TankStatusEnum_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδικ. Μείωση Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_LevelDecrease {
            get {
                return ResourceManager.GetString("TankStatusEnum_LevelDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδικ. Αυξηση Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_LevelIncrease {
            get {
                return ResourceManager.GetString("TankStatusEnum_LevelIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χαμηλή Στάθμη Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_LowLevel {
            get {
                return ResourceManager.GetString("TankStatusEnum_LowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκτός Λειτουργίας.
        /// </summary>
        internal static string TankStatusEnum_Offline {
            get {
                return ResourceManager.GetString("TankStatusEnum_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πώληση.
        /// </summary>
        internal static string TankStatusEnum_Selling {
            get {
                return ResourceManager.GetString("TankStatusEnum_Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναμονή Ηρεμίας Καυσίμου.
        /// </summary>
        internal static string TankStatusEnum_Waiting {
            get {
                return ResourceManager.GetString("TankStatusEnum_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.Invoice ADD
        ///	IsPrinted bit NULL,
        ///	Series nvarchar(10) NULL
        ///GO
        ///
        ///update Invoice Set IsPrinted = 1
        ///GO
        ///
        ///ALTER TABLE dbo.TankFilling ADD
        ///	SentDateTime datetime NULL,
        ///	ResponseCode nvarchar(500) NULL
        ///GO
        ///
        ///ALTER TABLE dbo.SalesTransaction ADD
        ///	SentDateTime datetime NULL,
        ///	ResponseCode nvarchar(500) NULL
        ///GO
        ///
        ///ALTER TABLE dbo.Balance ADD
        ///	SentDateTime datetime NULL,
        ///	ResponseCode nvarchar(500) NULL
        ///GO
        ///
        ///ALTER TABLE dbo.FuelTypePrice ADD
        ///	SentDateTime datetime NULL,
        ///	ResponseCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDatabase1 {
            get {
                return ResourceManager.GetString("UpdateDatabase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[TankLevelStartView]
        ///AS
        ///SELECT     [Level], TansDate, TankId, NEWID() AS ViewId
        ///FROM         (SELECT     dbo.TankSale.EndLevel AS [Level], dbo.SalesTransaction.TransactionTimeStamp AS TansDate, dbo.TankSale.TankId
        ///                       FROM          dbo.TankSale INNER JOIN
        ///                                              dbo.SalesTransaction ON dbo.TankSale.SalesTransactionId = dbo.SalesTransaction.SalesTransactionId
        ///                       UNION
        ///                       SELECT     Level [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDatabase2 {
            get {
                return ResourceManager.GetString("UpdateDatabase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[InvoicePrintView]
        ///AS
        ///SELECT     (SELECT     OptionValue
        ///                       FROM          dbo.[Option]
        ///                       WHERE      (OptionKey = &apos;CompanyName&apos;)) AS CompanyName,
        ///                          (SELECT     OptionValue
        ///                            FROM          dbo.[Option] AS Option_7
        ///                            WHERE      (OptionKey = &apos;CompanyOccupation&apos;)) AS CompanyOccupation,
        ///                          (SELECT     OptionValue
        ///                            FROM     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDatabase3 {
            get {
                return ResourceManager.GetString("UpdateDatabase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW [dbo].[TankSaleView]
        ///AS
        ///SELECT     NEWID() AS ViewId, dbo.TankSale.TankSaleId, dbo.TankSale.SalesTransactionId, dbo.TankSale.TankId, dbo.TankSale.StartVolume, dbo.TankSale.EndVolume, 
        ///                      dbo.TankSale.StartVolumeNormalized, dbo.TankSale.EndVolumeNormalized, dbo.TankSale.StartTemperature, dbo.TankSale.EndTemperature, dbo.TankSale.CRC, 
        ///                      dbo.TankSale.StartLevel, dbo.TankSale.EndLevel, dbo.TankSale.FuelDensity, dbo.SalesTransaction.NozzleId, dbo.SalesTrans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDatabase4 {
            get {
                return ResourceManager.GetString("UpdateDatabase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.TankFilling ADD
        ///	SignSignature nvarchar(255) NULL
        ///GO
        ///
        ///update  dbo.TankFilling set SignSignature = &apos;NOT Signed&apos;
        ///GO
        ///
        ///.
        /// </summary>
        internal static string UpdateDatabase5 {
            get {
                return ResourceManager.GetString("UpdateDatabase5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.InvoiceType ADD
        ///	IsInternal bit NULL
        ///GO
        ///
        ///CREATE NONCLUSTERED INDEX [idx_invoiceline_salestransaction]
        ///ON [dbo].[InvoiceLine] ([SaleTransactionId])
        ///GO
        ///
        ///CREATE NONCLUSTERED INDEX [idx_salestransaction_endlevel]
        ///ON [dbo].[TankSale] ([TankId])
        ///INCLUDE ([SalesTransactionId],[EndLevel])
        ///GO
        ///
        ///CREATE NONCLUSTERED INDEX [idx_titrimetry_height_volume]
        ///ON [dbo].[TitrimetryLevel] ([TitrimetryId])
        ///INCLUDE ([TitrimetryLevelId],[Height],[Volume])
        ///GO
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string UpdateDatabase6 {
            get {
                return ResourceManager.GetString("UpdateDatabase6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [dbo].[FuelType] ([FuelTypeId], [Name], [Code], [Color], [ThermalCoeficient], [EnumeratorValue], [BaseDensity]) VALUES (N&apos;53d9c499-22eb-44b8-9126-7bfd497b0980&apos;, N&apos;ΜΙΓΜΑ&apos;, N&apos;MIX&apos;, 0, CAST(0.001008000 AS Decimal(18, 9)), 99, CAST(800.000 AS Decimal(18, 3)))
        ///GO
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string UpdateDatabase7 {
            get {
                return ResourceManager.GetString("UpdateDatabase7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserChange {
            get {
                object obj = ResourceManager.GetObject("UserChange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserShift {
            get {
                object obj = ResourceManager.GetObject("UserShift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserShiftEnd {
            get {
                object obj = ResourceManager.GetObject("UserShiftEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
