//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαφορά Ισοζυγίου.
        /// </summary>
        internal static string AlertTypeEnum_BalanceDifference {
            get {
                return ResourceManager.GetString("AlertTypeEnum_BalanceDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Συνδεσης Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_CommunicationLossFuelPoint {
            get {
                return ResourceManager.GetString("AlertTypeEnum_CommunicationLossFuelPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Συνδεσης Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_CommunicationLossTank {
            get {
                return ResourceManager.GetString("AlertTypeEnum_CommunicationLossTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αδικαιολόγητη Απώλεια καυσίμου.
        /// </summary>
        internal static string AlertTypeEnum_FuelLoss {
            get {
                return ResourceManager.GetString("AlertTypeEnum_FuelLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_FuelPointError {
            get {
                return ResourceManager.GetString("AlertTypeEnum_FuelPointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διακοπή λειτουργίας προγράμματος.
        /// </summary>
        internal static string AlertTypeEnum_ProgramTermination {
            get {
                return ResourceManager.GetString("AlertTypeEnum_ProgramTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_TankAlert {
            get {
                return ResourceManager.GetString("AlertTypeEnum_TankAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Ογκομετρικού Πίνακα.
        /// </summary>
        internal static string AlertTypeEnum_TitrimetryDataChange {
            get {
                return ResourceManager.GetString("AlertTypeEnum_TitrimetryDataChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεδομένων Αντλίας.
        /// </summary>
        internal static string AlertTypeEnum_WrongDataFuelPoint {
            get {
                return ResourceManager.GetString("AlertTypeEnum_WrongDataFuelPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Δεδομένων Δεξαμενής.
        /// </summary>
        internal static string AlertTypeEnum_WrongDataTank {
            get {
                return ResourceManager.GetString("AlertTypeEnum_WrongDataTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γενικός Διαχειρηστής.
        /// </summary>
        internal static string ApplicationUserLevelEnum_Administrator {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συσκευή.
        /// </summary>
        internal static string ApplicationUserLevelEnum_Device {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαχειρηστής.
        /// </summary>
        internal static string ApplicationUserLevelEnum_SuperUser {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_SuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρήστης.
        /// </summary>
        internal static string ApplicationUserLevelEnum_User {
            get {
                return ResourceManager.GetString("ApplicationUserLevelEnum_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentLoop.
        /// </summary>
        internal static string CommunicationTypeEnum_CurrentLoop {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_CurrentLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS232.
        /// </summary>
        internal static string CommunicationTypeEnum_RS232 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS422.
        /// </summary>
        internal static string CommunicationTypeEnum_RS422 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485.
        /// </summary>
        internal static string CommunicationTypeEnum_RS485 {
            get {
                return ResourceManager.GetString("CommunicationTypeEnum_RS485", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραλαβή.
        /// </summary>
        internal static string DeliveryTypeEnum_Delivery {
            get {
                return ResourceManager.GetString("DeliveryTypeEnum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή.
        /// </summary>
        internal static string DeliveryTypeEnum_Drain {
            get {
                return ResourceManager.GetString("DeliveryTypeEnum_Drain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή.
        /// </summary>
        internal static string DeliveryTypeEnum_Return {
            get {
                return ResourceManager.GetString("DeliveryTypeEnum_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μετάγγιση (Εισαγωγή).
        /// </summary>
        internal static string DeliveryTypeEnum_TransfusionIn {
            get {
                return ResourceManager.GetString("DeliveryTypeEnum_TransfusionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μετάγγιση (Εξαγωγή).
        /// </summary>
        internal static string DeliveryTypeEnum_TransfusionOut {
            get {
                return ResourceManager.GetString("DeliveryTypeEnum_TransfusionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Στόμιο στο κανάλι {0} με διεύθυνση {1} έχει {2} λίτρα διαφορά..
        /// </summary>
        internal static string EventType_NozzleTotalDifference {
            get {
                return ResourceManager.GetString("EventType_NozzleTotalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Δεξαμενή στο κανάλι {0} με διεύθυνση {1} έχει {2} λίτρα διαφορά..
        /// </summary>
        internal static string EventType_TankTotalDifference {
            get {
                return ResourceManager.GetString("EventType_TankTotalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πίστωση.
        /// </summary>
        internal static string FinTransactionTypeEnum_Credit {
            get {
                return ResourceManager.GetString("FinTransactionTypeEnum_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χρέωση.
        /// </summary>
        internal static string FinTransactionTypeEnum_Debit {
            get {
                return ResourceManager.GetString("FinTransactionTypeEnum_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλειστή Παροχή.
        /// </summary>
        internal static string FlowStateEnum_ValveClosed {
            get {
                return ResourceManager.GetString("FlowStateEnum_ValveClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανοιχτή Παροχή.
        /// </summary>
        internal static string FlowStateEnum_ValveOpen {
            get {
                return ResourceManager.GetString("FlowStateEnum_ValveOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακύρωση.
        /// </summary>
        internal static string InvoiceTransformationTypeEnum_Cancelation {
            get {
                return ResourceManager.GetString("InvoiceTransformationTypeEnum_Cancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πολλά προς Ένα.
        /// </summary>
        internal static string InvoiceTransformationTypeEnum_ManyToOne {
            get {
                return ResourceManager.GetString("InvoiceTransformationTypeEnum_ManyToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ένα προς Πολλά.
        /// </summary>
        internal static string InvoiceTransformationTypeEnum_OneToMany {
            get {
                return ResourceManager.GetString("InvoiceTransformationTypeEnum_OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ένα προς Ένα.
        /// </summary>
        internal static string InvoiceTransformationTypeEnum_OneToOne {
            get {
                return ResourceManager.GetString("InvoiceTransformationTypeEnum_OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS 232.
        /// </summary>
        internal static string OPTConnectionTypeEnum_RS232 {
            get {
                return ResourceManager.GetString("OPTConnectionTypeEnum_RS232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP / IP.
        /// </summary>
        internal static string OPTConnectionTypeEnum_TCPIP {
            get {
                return ResourceManager.GetString("OPTConnectionTypeEnum_TCPIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Σειρά.
        /// </summary>
        internal static string OPTTypeEnum_Master {
            get {
                return ResourceManager.GetString("OPTTypeEnum_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παράλληλη Σύνδεση.
        /// </summary>
        internal static string OPTTypeEnum_Slave {
            get {
                return ResourceManager.GetString("OPTTypeEnum_Slave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μετρητά.
        /// </summary>
        internal static string PaymentTypeEnum_Cash {
            get {
                return ResourceManager.GetString("PaymentTypeEnum_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επί Πιστώσει.
        /// </summary>
        internal static string PaymentTypeEnum_Credit {
            get {
                return ResourceManager.GetString("PaymentTypeEnum_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πιστωτική Κάρτα.
        /// </summary>
        internal static string PaymentTypeEnum_CreditCard {
            get {
                return ResourceManager.GetString("PaymentTypeEnum_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κάρτα Στόλου.
        /// </summary>
        internal static string PaymentTypeEnum_FleetCard {
            get {
                return ResourceManager.GetString("PaymentTypeEnum_FleetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to βάσει Ημερομηνίας.
        /// </summary>
        internal static string ScheduleTypeEnum_Date {
            get {
                return ResourceManager.GetString("ScheduleTypeEnum_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εβδομαδιαίος.
        /// </summary>
        internal static string ScheduleTypeEnum_WayOfWeek {
            get {
                return ResourceManager.GetString("ScheduleTypeEnum_WayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αργία.
        /// </summary>
        internal static string ScheduleWeekDayEnum_DayOff {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρασκευή.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Friday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δευτέρα.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Monday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σάββατο.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Saturday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κυριακή.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Sunday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πέμπτη.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Thursday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρίτη.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Tuesday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τετάρτη.
        /// </summary>
        internal static string ScheduleWeekDayEnum_Wednesday {
            get {
                return ResourceManager.GetString("ScheduleWeekDayEnum_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ισοζύγιο.
        /// </summary>
        internal static string SendLogActionEnum_Balance {
            get {
                return ResourceManager.GetString("SendLogActionEnum_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Τιμής.
        /// </summary>
        internal static string SendLogActionEnum_FuelTypePrice {
            get {
                return ResourceManager.GetString("SendLogActionEnum_FuelTypePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πώληση.
        /// </summary>
        internal static string SendLogActionEnum_SalesTransaction {
            get {
                return ResourceManager.GetString("SendLogActionEnum_SalesTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συναγερμός.
        /// </summary>
        internal static string SendLogActionEnum_SystemEvent {
            get {
                return ResourceManager.GetString("SendLogActionEnum_SystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραλαβή.
        /// </summary>
        internal static string SendLogActionEnum_TankFilling {
            get {
                return ResourceManager.GetString("SendLogActionEnum_TankFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρνητικό (-).
        /// </summary>
        internal static string TransactionSignEnum_Negative {
            get {
                return ResourceManager.GetString("TransactionSignEnum_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θετικό (+).
        /// </summary>
        internal static string TransactionSignEnum_Positive {
            get {
                return ResourceManager.GetString("TransactionSignEnum_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραλαβή.
        /// </summary>
        internal static string TransactionTypeEnum_Delivery {
            get {
                return ResourceManager.GetString("TransactionTypeEnum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή.
        /// </summary>
        internal static string TransactionTypeEnum_Extraction {
            get {
                return ResourceManager.GetString("TransactionTypeEnum_Extraction", resourceCulture);
            }
        }
    }
}
