//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Communication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Communication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απόκλιση ισοζυγίου..
        /// </summary>
        internal static string AlertIdEnum_BalanceDifference {
            get {
                return ResourceManager.GetString("AlertIdEnum_BalanceDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απώλεια καυσίμου (κλοπή ή διαρροή).
        /// </summary>
        internal static string AlertIdEnum_FuelLoss {
            get {
                return ResourceManager.GetString("AlertIdEnum_FuelLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απώλεια επικοινωνείας με αντλία.
        /// </summary>
        internal static string AlertIdEnum_FuelPointCommunicationLoss {
            get {
                return ResourceManager.GetString("AlertIdEnum_FuelPointCommunicationLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναφορά Λάθους Αντλίας..
        /// </summary>
        internal static string AlertIdEnum_FuelPointError {
            get {
                return ResourceManager.GetString("AlertIdEnum_FuelPointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος δεδομένα μετρητών αντλίας μετά από επαναφορά..
        /// </summary>
        internal static string AlertIdEnum_FuelPointWrongData {
            get {
                return ResourceManager.GetString("AlertIdEnum_FuelPointWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τερματισμός προγράμματος..
        /// </summary>
        internal static string AlertIdEnum_ProgramTermination {
            get {
                return ResourceManager.GetString("AlertIdEnum_ProgramTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναφορά συναγερμού Δεξαμενής (Υπέρβαση Ορίου υπερπλήρωσης, Στάθμη νερού πέραν του νομιμου ορίου κ.τ.λ.).
        /// </summary>
        internal static string AlertIdEnum_TankAlert {
            get {
                return ResourceManager.GetString("AlertIdEnum_TankAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απώλεια επικοινωνίας με Δεξαμενή.
        /// </summary>
        internal static string AlertIdEnum_TankCommunicationLoss {
            get {
                return ResourceManager.GetString("AlertIdEnum_TankCommunicationLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα Πυκνότητας Καυσίμου.
        /// </summary>
        internal static string AlertIdEnum_TankDensityError {
            get {
                return ResourceManager.GetString("AlertIdEnum_TankDensityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος δεδομένα στάθμης καυσίμου δεξαμενής μετά από επαναφόρά..
        /// </summary>
        internal static string AlertIdEnum_TankWrongData {
            get {
                return ResourceManager.GetString("AlertIdEnum_TankWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μεταβολή στοιχείων Ογκομετρικού Πίνακα..
        /// </summary>
        internal static string AlertIdEnum_TitrimetryDataChange {
            get {
                return ResourceManager.GetString("AlertIdEnum_TitrimetryDataChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πετρέλαιο Κίνησης .
        /// </summary>
        internal static string FuelTypeEnum_Diesel {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πετρέλαιο Θέρμανσης.
        /// </summary>
        internal static string FuelTypeEnum_DieselHeat {
            get {
                return ResourceManager.GetString("FuelTypeEnum_DieselHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πετρέλαιο Θέρμανσης Premium.
        /// </summary>
        internal static string FuelTypeEnum_DieselHeatPremium {
            get {
                return ResourceManager.GetString("FuelTypeEnum_DieselHeatPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πετρέλαιο Κίνησης Premium.
        /// </summary>
        internal static string FuelTypeEnum_DieselPremium {
            get {
                return ResourceManager.GetString("FuelTypeEnum_DieselPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φωτιστικό Πετρέλαιο.
        /// </summary>
        internal static string FuelTypeEnum_Fotistiko {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Fotistiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φυσικό Αέριο (LPG).
        /// </summary>
        internal static string FuelTypeEnum_Lpg {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Lpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRP.
        /// </summary>
        internal static string FuelTypeEnum_Lrp {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Lrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μίγμα για Επαναδιύλιση.
        /// </summary>
        internal static string FuelTypeEnum_Mixture {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Mixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Χωρίς Επιλογή).
        /// </summary>
        internal static string FuelTypeEnum_None {
            get {
                return ResourceManager.GetString("FuelTypeEnum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αμόλυβδη 95.
        /// </summary>
        internal static string FuelTypeEnum_Unleaded95 {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Unleaded95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αμόλυβδη 95+.
        /// </summary>
        internal static string FuelTypeEnum_Unleaded95Plus {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Unleaded95Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αμόλυβδη 100.
        /// </summary>
        internal static string FuelTypeEnum_Unlieaded100 {
            get {
                return ResourceManager.GetString("FuelTypeEnum_Unlieaded100", resourceCulture);
            }
        }
    }
}
