//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFuelControl.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFuelControl.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ισοζύγιο.
        /// </summary>
        internal static string AlertData_Balance {
            get {
                return ResourceManager.GetString("AlertData_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημερομηνία Ισοζυγίου.
        /// </summary>
        internal static string AlertData_BalanceDate {
            get {
                return ResourceManager.GetString("AlertData_BalanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Καυσίμου.
        /// </summary>
        internal static string AlertData_CurrentFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θερμοκρασία Δεξαμενής.
        /// </summary>
        internal static string AlertData_CurrentTemperature {
            get {
                return ResourceManager.GetString("AlertData_CurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρέχων Όγκος Δεξαμενής.
        /// </summary>
        internal static string AlertData_CurrentVolume {
            get {
                return ResourceManager.GetString("AlertData_CurrentVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στάθμη Νερού.
        /// </summary>
        internal static string AlertData_CurrentWaterLevel {
            get {
                return ResourceManager.GetString("AlertData_CurrentWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τύπος Καυσίμου.
        /// </summary>
        internal static string AlertData_FuelType {
            get {
                return ResourceManager.GetString("AlertData_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενη στάθμη καυσίμου.
        /// </summary>
        internal static string AlertData_LastFuelLevel {
            get {
                return ResourceManager.GetString("AlertData_LastFuelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενη Θερμοκρασία Δεξαμενής.
        /// </summary>
        internal static string AlertData_LastTemperature {
            get {
                return ResourceManager.GetString("AlertData_LastTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενος Όγκος Δεξαμενής.
        /// </summary>
        internal static string AlertData_LastVolume {
            get {
                return ResourceManager.GetString("AlertData_LastVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενος συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_LastVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_LastVolumeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MaxHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστη επιτρεπόμενη στάθμη Νερού.
        /// </summary>
        internal static string AlertData_MaxWaterHeight {
            get {
                return ResourceManager.GetString("AlertData_MaxWaterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελάχιστο επιτρεπόμενο ύψος Καυσίμου.
        /// </summary>
        internal static string AlertData_MinHeight {
            get {
                return ResourceManager.GetString("AlertData_MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σύνολο διαφορας μετρητών μη εκπληρωμένων πωλήσεων.
        /// </summary>
        internal static string AlertData_TotalDifference {
            get {
                return ResourceManager.GetString("AlertData_TotalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνολικός όγκος πωλήσεων.
        /// </summary>
        internal static string AlertData_TotalVolumeCounter {
            get {
                return ResourceManager.GetString("AlertData_TotalVolumeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ογκος μη εκπληρωμένων πωλήσεων.
        /// </summary>
        internal static string AlertData_VolumeDifference {
            get {
                return ResourceManager.GetString("AlertData_VolumeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σειραικός Αριθμός Κατασκευαστή ({0}).
        /// </summary>
        internal static string DeviceSetting_CommunicationController_DeviceSerialNumber {
            get {
                return ResourceManager.GetString("DeviceSetting_CommunicationController_DeviceSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφραγγίδα Ηλεκτρονικών ({0}).
        /// </summary>
        internal static string DeviceSetting_Dispenser_DeviceSeal {
            get {
                return ResourceManager.GetString("DeviceSetting_Dispenser_DeviceSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σειραικός Αριθμός Κατασκευαστή ({0}).
        /// </summary>
        internal static string DeviceSetting_Dispenser_DeviceSerialNumber {
            get {
                return ResourceManager.GetString("DeviceSetting_Dispenser_DeviceSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τύπος Αντλίας ({0}).
        /// </summary>
        internal static string DeviceSetting_Dispenser_DeviceType {
            get {
                return ResourceManager.GetString("DeviceSetting_Dispenser_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πώληση με Κάρτα.
        /// </summary>
        internal static string DeviceSetting_Dispenser_FleetSales {
            get {
                return ResourceManager.GetString("DeviceSetting_Dispenser_FleetSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφραγγίδα Ογκομετρητή ({0}).
        /// </summary>
        internal static string DeviceSetting_Nozzle_VolumeCounterSeal {
            get {
                return ResourceManager.GetString("DeviceSetting_Nozzle_VolumeCounterSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφραγγίδα Δεξαμενής ({0}).
        /// </summary>
        internal static string DeviceSetting_Tank_DeviceSeal {
            get {
                return ResourceManager.GetString("DeviceSetting_Tank_DeviceSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελεγκτής.
        /// </summary>
        internal static string DeviceType_CommunicationController {
            get {
                return ResourceManager.GetString("DeviceType_CommunicationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπολογιστής.
        /// </summary>
        internal static string DeviceType_Computer {
            get {
                return ResourceManager.GetString("DeviceType_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αντλία Καυσίμου.
        /// </summary>
        internal static string DeviceType_Dispenser {
            get {
                return ResourceManager.GetString("DeviceType_Dispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πληκτρολόγιο.
        /// </summary>
        internal static string DeviceType_Keyboard {
            get {
                return ResourceManager.GetString("DeviceType_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ποντίκι.
        /// </summary>
        internal static string DeviceType_Mouse {
            get {
                return ResourceManager.GetString("DeviceType_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακροσωλήνιο.
        /// </summary>
        internal static string DeviceType_Nozzle {
            get {
                return ResourceManager.GetString("DeviceType_Nozzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκτυπωτής.
        /// </summary>
        internal static string DeviceType_Printer {
            get {
                return ResourceManager.GetString("DeviceType_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οθόνη.
        /// </summary>
        internal static string DeviceType_Screen {
            get {
                return ResourceManager.GetString("DeviceType_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεξαμενή.
        /// </summary>
        internal static string DeviceType_Tank {
            get {
                return ResourceManager.GetString("DeviceType_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φορολογικός Μηχανιοσμός.
        /// </summary>
        internal static string DeviceType_TaxDevice {
            get {
                return ResourceManager.GetString("DeviceType_TaxDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvoiceCanceled {
            get {
                object obj = ResourceManager.GetObject("InvoiceCanceled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Αναγωγή στους 15ο C δεν είναι σωστή. Η ανεγαγμένη ποσότητα στους 15ο C θα έπρεπε να είναι {0:N2}.
        /// </summary>
        internal static string InvoiceLine_RecieveNormalizationError {
            get {
                return ResourceManager.GetString("InvoiceLine_RecieveNormalizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvoiceReplaced {
            get {
                object obj = ResourceManager.GetObject("InvoiceReplaced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvoiceValid {
            get {
                object obj = ResourceManager.GetObject("InvoiceValid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχει τιμή για τον επιλεμένο τύπο καυσίμου ({0})..
        /// </summary>
        internal static string SalesTransactionValidator_FuelTypePriceNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_FuelTypePriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε τιμή για την πώληση που κάνετε..
        /// </summary>
        internal static string SalesTransactionValidator_NozzlePriceNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_NozzlePriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε άνοιγμα περιόδου για το στόμιο {0}..
        /// </summary>
        internal static string SalesTransactionValidator_NozzleUsagePriodNotFound {
            get {
                return ResourceManager.GetString("SalesTransactionValidator_NozzleUsagePriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπόρεσε να δημιουργηθεί καταχώρηση τιμής για την δεξαμενή {0}..
        /// </summary>
        internal static string TankFillingValidator_TankPriceCreationFailed {
            get {
                return ResourceManager.GetString("TankFillingValidator_TankPriceCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε άνοιγμα περιόδου για την δεξαμενή {0}..
        /// </summary>
        internal static string TankFillingValidator_TankUsagePriodNotFound {
            get {
                return ResourceManager.GetString("TankFillingValidator_TankUsagePriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε ανοιχτή χρήση για την {0:ddd dd/MM/yyyy}...
        /// </summary>
        internal static string UsagePeriod_PerioNotFound {
            get {
                return ResourceManager.GetString("UsagePeriod_PerioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H περίοδος χρήσης της εγγραφής είναι κλειδωμένη. Δεν έγιναν αλλαγές...
        /// </summary>
        internal static string UsagePeriodLocked {
            get {
                return ResourceManager.GetString("UsagePeriodLocked", resourceCulture);
            }
        }
    }
}
