//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exedron.MyData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exedron.MyData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;address&gt;
        ///    &lt;street&gt;[street]&lt;/street&gt;
        ///    &lt;number&gt;[number]&lt;/number&gt;
        ///    &lt;postalCode&gt;[postalcode]&lt;/postalCode&gt;
        ///    &lt;city&gt;[city]&lt;/city&gt;
        ///&lt;/address&gt;
        ///.
        /// </summary>
        internal static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfLong xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;[array]&lt;/ArrayOfLong&gt;.
        /// </summary>
        internal static string CorrelatedInvoices {
            get {
                return ResourceManager.GetString("CorrelatedInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;incomeClassification&gt;
        ///  &lt;icls:classificationType&gt;[classificationtype]&lt;/icls:classificationType&gt;
        ///  &lt;icls:classificationCategory&gt;[classificationcategory]&lt;/icls:classificationCategory&gt;
        ///  &lt;icls:amount&gt;[amount]&lt;/icls:amount&gt;
        ///  &lt;icls:id&gt;[id]&lt;/icls:id&gt;
        ///&lt;/incomeClassification&gt;.
        /// </summary>
        internal static string IncomeClassification {
            get {
                return ResourceManager.GetString("IncomeClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;invoice&gt;
        ///  [issuer]
        ///  [counterpart]
        ///  [invoiceheader]
        ///  &lt;paymentMethods&gt;
        ///    [paymentmethoddetails]
        ///  &lt;/paymentMethods&gt;
        ///  [invoicedetails]
        ///  [invoicesummary]
        ///&lt;/invoice&gt;.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;invoiceDetails&gt;
        ///    &lt;lineNumber&gt;[linenumber]&lt;/lineNumber&gt;
        ///    &lt;quantity&gt;[quantity]&lt;/quantity&gt;
        ///    &lt;measurementUnit&gt;[measurementunit]&lt;/measurementUnit&gt;
        ///    &lt;netValue&gt;[netvalue]&lt;/netValue&gt;
        ///    &lt;vatCategory&gt;[vatcategory]&lt;/vatCategory&gt;
        ///    &lt;vatAmount&gt;[vatamount]&lt;/vatAmount&gt;
        ///	&lt;vatExemptionCategory&gt;[vatexemptioncategory]&lt;/vatExemptionCategory&gt;
        ///    &lt;deductionsAmount&gt;[deductionsamount]&lt;/deductionsAmount&gt;
        ///    [incomeclassification]
        ///&lt;/invoiceDetails&gt;.
        /// </summary>
        internal static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;InvoicesDoc xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:icls=&quot;https://www.aade.gr/myDATA/incomeClassificaton/v1.0&quot; xmlns:ecls=&quot;https://www.aade.gr/myDATA/expensesClassificaton/v1.0&quot; xmlns=&quot;http://www.aade.gr/myDATA/invoice/v1.0&quot;&gt;
        ///  [invoices]
        ///&lt;/InvoicesDoc&gt;.
        /// </summary>
        internal static string InvoiceDoc {
            get {
                return ResourceManager.GetString("InvoiceDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;invoiceHeader&gt;
        ///    &lt;series&gt;[series]&lt;/series&gt;
        ///    &lt;aa&gt;[aa]&lt;/aa&gt;
        ///    &lt;issueDate&gt;[issuedate]&lt;/issueDate&gt;
        ///    &lt;invoiceType&gt;[invoicetype]&lt;/invoiceType&gt;
        ///    &lt;vatPaymentSuspension&gt;[vatpaymentsuspension]&lt;/vatPaymentSuspension&gt;
        ///    &lt;currency&gt;[currency]&lt;/currency&gt;
        ///	&lt;correlatedInvoices&gt;[correlatedinvoices]&lt;/correlatedInvoices&gt;
        ///	&lt;movePurpose&gt;[movepurpose]&lt;/movePurpose&gt;
        ///	&lt;otherDeliveryNoteHeader&gt;[otherDeliveryNoteHeader]&lt;/otherDeliveryNoteHeader&gt;
        ///&lt;/invoiceHeader&gt;.
        /// </summary>
        internal static string InvoiceHeader {
            get {
                return ResourceManager.GetString("InvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;invoiceSummary&gt;
        ///    &lt;totalNetValue&gt;[totalnetvalue]&lt;/totalNetValue&gt;
        ///    &lt;totalVatAmount&gt;[totalvatamount]&lt;/totalVatAmount&gt;
        ///    &lt;totalWithheldAmount&gt;[totalwithheldamount]&lt;/totalWithheldAmount&gt;
        ///    &lt;totalFeesAmount&gt;[totalfeesamount]&lt;/totalFeesAmount&gt;
        ///    &lt;totalStampDutyAmount&gt;[totalstampdutyamount]&lt;/totalStampDutyAmount&gt;
        ///    &lt;totalOtherTaxesAmount&gt;[totalothertaxesamount]&lt;/totalOtherTaxesAmount&gt;
        ///    &lt;totalDeductionsAmount&gt;[totaldeductionsamount]&lt;/totalDeductionsAmount&gt;
        ///    &lt;totalGrossValue&gt;[totalgrossva [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvoiceSummary {
            get {
                return ResourceManager.GetString("InvoiceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;otherDeliveryNoteHeader&gt;
        ///    &lt;loadingAddress&gt;[loadingAddress]&lt;loadingAddress&gt;
        ///	&lt;deliveryAddress&gt;[deliveryAddress]&lt;deliveryAddress&gt;
        ///&lt;/otherDeliveryNoteHeader&gt;.
        /// </summary>
        internal static string OtherDeliveryNoteHeader {
            get {
                return ResourceManager.GetString("OtherDeliveryNoteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;[partytype]&gt;
        ///    &lt;vatNumber&gt;[vatnumber]&lt;/vatNumber&gt;
        ///    &lt;country&gt;[country]&lt;/country&gt;
        ///    &lt;branch&gt;[branch]&lt;/branch&gt;
        ///	&lt;name&gt;[name]&lt;/name&gt;
        ///	[address]
        ///&lt;/[partytype]&gt;.
        /// </summary>
        internal static string PartyType {
            get {
                return ResourceManager.GetString("PartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;paymentMethodDetails&gt;
        ///  &lt;type&gt;[type]&lt;/type&gt;
        ///  &lt;amount&gt;[amount]&lt;/amount&gt;
        ///  &lt;paymentMethodInfo&gt;[paymentmethodinfo]&lt;/paymentMethodInfo&gt;
        ///&lt;/paymentMethodDetails&gt;.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
    }
}
