#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TitrationExporter;

namespace TitrationExporter	
{
	public partial class DatabaseModel : OpenAccessContext, IDatabaseModelUnitOfWork
	{
		private static string connectionStringName = @"ASFuelControlDB_KatsikakiConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("DatabaseModel.rlinq");
		
		public DatabaseModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public DatabaseModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public DatabaseModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public DatabaseModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public DatabaseModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<TitrimetryLevel> TitrimetryLevels 
		{
			get
			{
				return this.GetAll<TitrimetryLevel>();
			}
		}
		
		public IQueryable<Titrimetry> Titrimetries 
		{
			get
			{
				return this.GetAll<Titrimetry>();
			}
		}
		
		public IQueryable<Tank> Tanks 
		{
			get
			{
				return this.GetAll<Tank>();
			}
		}
		
		public IQueryable<FuelType> FuelTypes 
		{
			get
			{
				return this.GetAll<FuelType>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of DatabaseModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of DatabaseModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IDatabaseModelUnitOfWork : IUnitOfWork
	{
		IQueryable<TitrimetryLevel> TitrimetryLevels
		{
			get;
		}
		IQueryable<Titrimetry> Titrimetries
		{
			get;
		}
		IQueryable<Tank> Tanks
		{
			get;
		}
		IQueryable<FuelType> FuelTypes
		{
			get;
		}
	}
}
namespace TitrationExporter	
{
	public partial class TitrimetryLevel
	{
		private Guid _titrimetryLevelId;
		public virtual Guid TitrimetryLevelId
		{
			get
			{
				return this._titrimetryLevelId;
			}
			set
			{
				this._titrimetryLevelId = value;
			}
		}
		
		private Guid? _titrimetryId;
		public virtual Guid? TitrimetryId
		{
			get
			{
				return this._titrimetryId;
			}
			set
			{
				this._titrimetryId = value;
			}
		}
		
		private decimal? _height;
		public virtual decimal? Height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		
		private decimal? _volume;
		public virtual decimal? Volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				this._volume = value;
			}
		}
		
		private Titrimetry _titrimetry;
		public virtual Titrimetry Titrimetry
		{
			get
			{
				return this._titrimetry;
			}
			set
			{
				this._titrimetry = value;
			}
		}
		
	}
}
namespace TitrationExporter	
{
	public partial class Titrimetry
	{
		private Guid _titrimetryId;
		public virtual Guid TitrimetryId
		{
			get
			{
				return this._titrimetryId;
			}
			set
			{
				this._titrimetryId = value;
			}
		}
		
		private Guid? _tankId;
		public virtual Guid? TankId
		{
			get
			{
				return this._tankId;
			}
			set
			{
				this._tankId = value;
			}
		}
		
		private DateTime? _titrationDate;
		public virtual DateTime? TitrationDate
		{
			get
			{
				return this._titrationDate;
			}
			set
			{
				this._titrationDate = value;
			}
		}
		
		private DateTime? _printDate;
		public virtual DateTime? PrintDate
		{
			get
			{
				return this._printDate;
			}
			set
			{
				this._printDate = value;
			}
		}
		
		private string _documentSign;
		public virtual string DocumentSign
		{
			get
			{
				return this._documentSign;
			}
			set
			{
				this._documentSign = value;
			}
		}
		
		private Tank _tank;
		public virtual Tank Tank
		{
			get
			{
				return this._tank;
			}
			set
			{
				this._tank = value;
			}
		}
		
		private IList<TitrimetryLevel> _titrimetryLevels = new List<TitrimetryLevel>();
		public virtual IList<TitrimetryLevel> TitrimetryLevels
		{
			get
			{
				return this._titrimetryLevels;
			}
		}
		
	}
}
namespace TitrationExporter	
{
	public partial class Tank
	{
		private Guid _tankId;
		public virtual Guid TankId
		{
			get
			{
				return this._tankId;
			}
			set
			{
				this._tankId = value;
			}
		}
		
		private Guid _fuelTypeId;
		public virtual Guid FuelTypeId
		{
			get
			{
				return this._fuelTypeId;
			}
			set
			{
				this._fuelTypeId = value;
			}
		}
		
		private decimal _totalVolume;
		public virtual decimal TotalVolume
		{
			get
			{
				return this._totalVolume;
			}
			set
			{
				this._totalVolume = value;
			}
		}
		
		private decimal _offsetVolume;
		public virtual decimal OffsetVolume
		{
			get
			{
				return this._offsetVolume;
			}
			set
			{
				this._offsetVolume = value;
			}
		}
		
		private int _physicalState;
		public virtual int PhysicalState
		{
			get
			{
				return this._physicalState;
			}
			set
			{
				this._physicalState = value;
			}
		}
		
		private int _channel;
		public virtual int Channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		
		private int _address;
		public virtual int Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private Guid _atgProbeTypeId;
		public virtual Guid AtgProbeTypeId
		{
			get
			{
				return this._atgProbeTypeId;
			}
			set
			{
				this._atgProbeTypeId = value;
			}
		}
		
		private Guid _communicationControllerId;
		public virtual Guid CommunicationControllerId
		{
			get
			{
				return this._communicationControllerId;
			}
			set
			{
				this._communicationControllerId = value;
			}
		}
		
		private decimal _maxWaterHeight;
		public virtual decimal MaxWaterHeight
		{
			get
			{
				return this._maxWaterHeight;
			}
			set
			{
				this._maxWaterHeight = value;
			}
		}
		
		private decimal _minFuelHeight;
		public virtual decimal MinFuelHeight
		{
			get
			{
				return this._minFuelHeight;
			}
			set
			{
				this._minFuelHeight = value;
			}
		}
		
		private decimal _maxFuelHeight;
		public virtual decimal MaxFuelHeight
		{
			get
			{
				return this._maxFuelHeight;
			}
			set
			{
				this._maxFuelHeight = value;
			}
		}
		
		private int _tankNumber;
		public virtual int TankNumber
		{
			get
			{
				return this._tankNumber;
			}
			set
			{
				this._tankNumber = value;
			}
		}
		
		private string _tankSerialNumber;
		public virtual string TankSerialNumber
		{
			get
			{
				return this._tankSerialNumber;
			}
			set
			{
				this._tankSerialNumber = value;
			}
		}
		
		private decimal _fuelLevel;
		public virtual decimal FuelLevel
		{
			get
			{
				return this._fuelLevel;
			}
			set
			{
				this._fuelLevel = value;
			}
		}
		
		private decimal _waterLevel;
		public virtual decimal WaterLevel
		{
			get
			{
				return this._waterLevel;
			}
			set
			{
				this._waterLevel = value;
			}
		}
		
		private decimal _temperatire;
		public virtual decimal Temperatire
		{
			get
			{
				return this._temperatire;
			}
			set
			{
				this._temperatire = value;
			}
		}
		
		private bool? _isVirtual;
		public virtual bool? IsVirtual
		{
			get
			{
				return this._isVirtual;
			}
			set
			{
				this._isVirtual = value;
			}
		}
		
		private decimal _offestWater;
		public virtual decimal OffestWater
		{
			get
			{
				return this._offestWater;
			}
			set
			{
				this._offestWater = value;
			}
		}
		
		private decimal? _orderLimit;
		public virtual decimal? OrderLimit
		{
			get
			{
				return this._orderLimit;
			}
			set
			{
				this._orderLimit = value;
			}
		}
		
		private FuelType _fuelType;
		public virtual FuelType FuelType
		{
			get
			{
				return this._fuelType;
			}
			set
			{
				this._fuelType = value;
			}
		}
		
		private IList<Titrimetry> _titrimetries = new List<Titrimetry>();
		public virtual IList<Titrimetry> Titrimetries
		{
			get
			{
				return this._titrimetries;
			}
		}
		
	}
}
namespace TitrationExporter	
{
	public partial class FuelType
	{
		private Guid _fuelTypeId;
		public virtual Guid FuelTypeId
		{
			get
			{
				return this._fuelTypeId;
			}
			set
			{
				this._fuelTypeId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _code;
		public virtual string Code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		
		private int? _color;
		public virtual int? Color
		{
			get
			{
				return this._color;
			}
			set
			{
				this._color = value;
			}
		}
		
		private decimal _thermalCoeficient;
		public virtual decimal ThermalCoeficient
		{
			get
			{
				return this._thermalCoeficient;
			}
			set
			{
				this._thermalCoeficient = value;
			}
		}
		
		private int _enumeratorValue;
		public virtual int EnumeratorValue
		{
			get
			{
				return this._enumeratorValue;
			}
			set
			{
				this._enumeratorValue = value;
			}
		}
		
		private decimal _baseDensity;
		public virtual decimal BaseDensity
		{
			get
			{
				return this._baseDensity;
			}
			set
			{
				this._baseDensity = value;
			}
		}
		
		private IList<Tank> _tanks = new List<Tank>();
		public virtual IList<Tank> Tanks
		{
			get
			{
				return this._tanks;
			}
		}
		
	}
}
#pragma warning restore 1591
