namespace ASFuelControl.Windows.UI.Forms
{
    partial class DispenserDiscountForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn4 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            this.nozzleBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.nozzleRadGridView = new Telerik.WinControls.UI.RadGridView();
            this.radLabel10 = new Telerik.WinControls.UI.RadLabel();
            this.discountText1 = new Telerik.WinControls.UI.RadTextBox();
            this.radButton1 = new Telerik.WinControls.UI.RadButton();
            this.radButton2 = new Telerik.WinControls.UI.RadButton();
            this.radButton3 = new Telerik.WinControls.UI.RadButton();
            this.panel1 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.nozzleBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nozzleRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nozzleRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radLabel10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.discountText1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton3)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // nozzleBindingSource
            // 
            this.nozzleBindingSource.DataSource = typeof(ASFuelControl.Data.Nozzle);
            // 
            // nozzleRadGridView
            // 
            this.nozzleRadGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.nozzleRadGridView.Enabled = false;
            this.nozzleRadGridView.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.nozzleRadGridView.Location = new System.Drawing.Point(12, 39);
            // 
            // nozzleRadGridView
            // 
            this.nozzleRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.nozzleRadGridView.MasterTemplate.AllowDeleteRow = false;
            this.nozzleRadGridView.MasterTemplate.AutoGenerateColumns = false;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "OrderId";
            gridViewDecimalColumn1.HeaderText = "Ακροσωλήνιο";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "OrderId";
            gridViewDecimalColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.FieldName = "Description";
            gridViewTextBoxColumn1.HeaderText = "Περιγραφή";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Description";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 180;
            gridViewDecimalColumn2.FieldName = "FuelType.CurrentPrice";
            gridViewDecimalColumn2.FormatString = "{0:N3}";
            gridViewDecimalColumn2.HeaderText = "Τιμή Λίτρου";
            gridViewDecimalColumn2.Name = "UnitPrice";
            gridViewDecimalColumn2.ReadOnly = true;
            gridViewDecimalColumn2.Width = 100;
            gridViewDecimalColumn3.FieldName = "DiscountPercentage";
            gridViewDecimalColumn3.FormatString = "{0:N2}";
            gridViewDecimalColumn3.HeaderText = "% Εκπτωσης";
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "DiscountPercentage";
            gridViewDecimalColumn3.Width = 100;
            gridViewDecimalColumn4.FieldName = "DiscountUnitPrice";
            gridViewDecimalColumn4.FormatString = "{0:N3}";
            gridViewDecimalColumn4.HeaderText = "€ Εκπτωσης";
            gridViewDecimalColumn4.IsAutoGenerated = true;
            gridViewDecimalColumn4.Name = "DiscountUnitPrice";
            gridViewDecimalColumn4.ReadOnly = true;
            gridViewDecimalColumn4.Width = 100;
            this.nozzleRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewDecimalColumn2,
            gridViewDecimalColumn3,
            gridViewDecimalColumn4});
            this.nozzleRadGridView.MasterTemplate.DataSource = this.nozzleBindingSource;
            this.nozzleRadGridView.MasterTemplate.EnableGrouping = false;
            this.nozzleRadGridView.Name = "nozzleRadGridView";
            this.nozzleRadGridView.ShowGroupPanel = false;
            this.nozzleRadGridView.Size = new System.Drawing.Size(567, 175);
            this.nozzleRadGridView.TabIndex = 0;
            this.nozzleRadGridView.Text = "radGridView2";
            // 
            // radLabel10
            // 
            this.radLabel10.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.radLabel10.Location = new System.Drawing.Point(12, 12);
            this.radLabel10.Name = "radLabel10";
            this.radLabel10.Size = new System.Drawing.Size(58, 21);
            this.radLabel10.TabIndex = 3;
            this.radLabel10.Text = "Κωδικός";
            // 
            // discountText1
            // 
            this.discountText1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.discountText1.Location = new System.Drawing.Point(87, 11);
            this.discountText1.Name = "discountText1";
            this.discountText1.PasswordChar = '*';
            this.discountText1.Size = new System.Drawing.Size(138, 23);
            this.discountText1.TabIndex = 2;
            // 
            // radButton1
            // 
            this.radButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.radButton1.Enabled = false;
            this.radButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.radButton1.Location = new System.Drawing.Point(12, 220);
            this.radButton1.Name = "radButton1";
            this.radButton1.Size = new System.Drawing.Size(110, 24);
            this.radButton1.TabIndex = 4;
            this.radButton1.Text = "Επιλογή";
            this.radButton1.Click += new System.EventHandler(this.radButton1_Click);
            // 
            // radButton2
            // 
            this.radButton2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.radButton2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.radButton2.Location = new System.Drawing.Point(469, 220);
            this.radButton2.Name = "radButton2";
            this.radButton2.Size = new System.Drawing.Size(110, 24);
            this.radButton2.TabIndex = 5;
            this.radButton2.Text = "Άκυρο";
            this.radButton2.Click += new System.EventHandler(this.radButton2_Click);
            // 
            // radButton3
            // 
            this.radButton3.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(161)));
            this.radButton3.Location = new System.Drawing.Point(230, 9);
            this.radButton3.Name = "radButton3";
            this.radButton3.Size = new System.Drawing.Size(110, 25);
            this.radButton3.TabIndex = 6;
            this.radButton3.Text = "Εισαγωγή";
            this.radButton3.Click += new System.EventHandler(this.radButton3_Click);
            // 
            // panel1
            // 
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.radLabel10);
            this.panel1.Controls.Add(this.radButton2);
            this.panel1.Controls.Add(this.radButton3);
            this.panel1.Controls.Add(this.radButton1);
            this.panel1.Controls.Add(this.discountText1);
            this.panel1.Controls.Add(this.nozzleRadGridView);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(593, 258);
            this.panel1.TabIndex = 7;
            // 
            // DispenserDiscountForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(593, 258);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "DispenserDiscountForm";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Εκπτωση Επόμενης Πώλησης";
            ((System.ComponentModel.ISupportInitialize)(this.nozzleBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nozzleRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nozzleRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radLabel10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.discountText1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radButton3)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource nozzleBindingSource;
        private Telerik.WinControls.UI.RadGridView nozzleRadGridView;
        private Telerik.WinControls.UI.RadLabel radLabel10;
        private Telerik.WinControls.UI.RadTextBox discountText1;
        private Telerik.WinControls.UI.RadButton radButton1;
        private Telerik.WinControls.UI.RadButton radButton2;
        private Telerik.WinControls.UI.RadButton radButton3;
        private System.Windows.Forms.Panel panel1;

    }
}